### ISSUE TITLE
publish: handle the "u-in-reply-to h-cite" pattern

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#101]
...ie in-reply-to can be an h-cite dict, not just a flat string url. thanks to @kartikprabhu for the find! details: http://indiewebcamp.com/in-reply-to

example mf2py parsed output:

``` json
"in-reply-to": [
  { "properties": {
      "name": [ "http://www.warrenellis.com/?p=15111"],
      "url": [ "http://www.warrenellis.com/?p=15111"]
      },
    "type": ["h-cite"],
    "value": "http://www.warrenellis.com/?p=15111"
    },
    { "properties": {
      "name": ["https://twitter.com/warrenellis/status/446329231505883136"],
      "url": [ "https://twitter.com/warrenellis/status/446329231505883136"]
      },
    "type": ["h-cite"],
    "value": "https://twitter.com/warrenellis/status/446329231505883136"
    }
```

stack trace below. simplest fix is to update https://github.com/snarfed/activitystreams-unofficial/blob/master/microformats2.py#L266 to detect this and extract the string url(s).

``` py
Error: unhashable type: 'dict'
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/2.374535217061261364/publish.py", line 145, in post
    preview = self.source.as_source.preview_create(obj, include_link=True)
  File "/base/data/home/apps/s~brid-gy/2.374535217061261364/activitystreams/twitter.py", line 327, in preview_create
    return self._create(obj, preview=True, include_link=include_link)
  File "/base/data/home/apps/s~brid-gy/2.374535217061261364/activitystreams/twitter.py", line 349, in _create
    base_id, base_url = self.base_object(obj)
  File "/base/data/home/apps/s~brid-gy/2.374535217061261364/activitystreams/source.py", line 475, in base_object
    domain = urlparse.urlparse(base_obj.get('url', '')).netloc
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urlparse.py", line 142, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urlparse.py", line 175, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'
```

**Comment by miklb** [comment]
after talking with @aaronpk it seems this may not be working any longer based on a current reply on my site

https://miklb.com/blog/2018/09/02/4301/

that did not track as a reply on Twitter from bridgy

**Comment by miklb** [comment]
false alarm, it appears to be an issue replying via micropub in WordPress and the order things are getting fired in. Debugging now.
