### ISSUE TITLE
Twitter App authorization redirects to localhost:8080

### ISSUE THREAD

**Issue by jpcaruana** [snarfed/bridgy#1108]
when I click on twitter syndication https://api.twitter.com/oauth/authorize?oauth_token=xxxx, Authorize app redirects to http://localhost:8080/twitter/delete/finish?oauth_token=xxx&oauth_verifier=yyy

Also sending webmention to https://brid.gy/publish/twitter responds with a 400 error.

Am I missing something here?

**Comment by jpcaruana** [comment]
I found a stack trace for the aformentioned 400 error: Read-only application cannot POST

```python
W 2022-01-26 13:02:40.993623+00:00 Disabling source due to: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/workspace/publish.py", line 243, in _run
    result = self.attempt_single_item(item)
  File "/workspace/publish.py", line 402, in attempt_single_item
    result = self.source.gr_source.create(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py", line 661, in create
    return self._create(obj, preview=False, include_link=include_link,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py", line 872, in _create
    resp = self.urlopen(API_POST_TWEET, data=urllib.parse.urlencode(sorted(data)))
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py", line 1111, in urlopen
    return request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py", line 1089, in request
    resp = twitter_auth.signed_urlopen(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/twitter_auth.py", line 59, in signed_urlopen
    return util.urlopen(urllib.request.Request(url, headers=headers, **kwargs))
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/webutil/util.py", line 1521, in urlopen
    return urllib.request.urlopen(url_or_req, *args, **kwargs)
  File "/opt/python3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, ... hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
I 2022-01-26 13:02:41.154467+00:00 publish: Error: {"request":"\/1.1\/statuses\/update.json","error":"Read-only application cannot POST."} HTTP Error 401: Unauthorized
I 2022-01-26 13:02:41.208886+00:00 Returning 400: {'error': 'Error: {"request":"\\/1.1\\/statuses\\/update.json","error":"Read-only application cannot POST."} HTTP Error 401: Unauthorized'} {'response': <Response 152 bytes [200 OK]>}
E 2022-01-26 13:02:41.209776+00:00 <class 'werkzeug.exceptions.BadRequest'>: 400 Bad Request: {'error': 'Error: {"request":"\\/1.1\\/statuses\\/update.json","error":"Read-only application cannot POST."} HTTP Error 401: Unauthorized'}
```

**Comment by snarfed** [comment]
Whoops! That is definitely not right. Thanks for reporting, will fix.

**Comment by snarfed** [comment]
Fixed. Thanks again, sorry for the trouble!

**Comment by snarfed** [comment]
Actually, I'm going to leave this open until I fix the root cause, but the deployed version on https://brid.gy/ is working fine now.

**Comment by jpcaruana** [comment]
Yes thank you for your time!

**Comment by snarfed** [comment]
Still trying to debug the root cause here. A few data points:
* Happened between the 20220121t064908 and 20220124t120047 deploys.
* Pretty sure both of those deploys were from head on the main branch.
* Reproduces on the latest deploy, 20220127t080339 (not serving), also from head on all repos.
* Other silos are unaffected, eg I can log in with Mastodon and Flickr fine on that ^ deploy.
* No obviously relevant changes to Twitter code or other config in this time window:
  * https://github.com/snarfed/bridgy/compare/ce62d5ef903ec39185f69edeb22c8335d5f5f468...snarfed:main
  * https://github.com/snarfed/granary/compare/fe12824fe20e6e67cf647f2787efb2d4b40cc774...snarfed:main
  * https://github.com/snarfed/oauth-dropins/compare/3445cee929cc1797f4284f92d1cf822d026d51f9...snarfed:main

**Comment by snarfed** [comment]
Aha. It was probably the tweepy 4.0 upgrade 🤦 https://github.com/snarfed/oauth-dropins/pull/66

**Comment by snarfed** [comment]
Confirmed, except surprisingly it was tweepy 4.4 => 4.5 that did it, not 3.x to 4.0. So much for semver.

**Comment by jpcaruana** [comment]
> Confirmed, except surprisingly it was tweepy 4.4 => 4.5 that did it, not 3.x to 4.0. So much for semver.

well catched! So sad semver was not respected here

Many thanks again

**Comment by snarfed** [comment]
0c5cd60ecc19f5ce86027551bd705b23034fe6e0
