### ISSUE TITLE
twitter: read only app?

### ISSUE THREAD

**Issue by jpcaruana** [snarfed/bridgy#1311]
I had an issue with publishing to twitter, see https://brid.gy/log?start_time=1664867440&key=agdicmlkLWd5cmgLEg1QdWJsaXNoZWRQYWdlIkFodHRwczovL2pwLmNhcnVhbmEuZnIvbm90ZXMvMjAyMi8xMC8wNC9na3BsdWdpbmJhYnktYy1lc3QtbWlndWVsLwwLEgdQdWJsaXNoGICAmMr7lIcLDA&module=default

```python
I 2022-10-04 07:10:40.315163+00:00 [requests.head](http://requests.head/) https://twitter.com/GKPlugInBaby/status/1577029756955959297?t=Z49XKmVZJ7bihqP-4CHvuw&s=19 {'headers': {}}
I 2022-10-04 07:10:40.511783+00:00 Received 200
I 2022-10-04 07:10:40.546629+00:00 no refresh_token
I 2022-10-04 07:10:40.556413+00:00 urlopen POST https://api.twitter.com/1.1/statuses/update.json?auto_populate_reply_metadata=true&in_reply_to_status_id=1577029756955959297&status=c%E2%80%99est+Miguel+Sapochnik+qui+a+r%C3%A9alis%C3%A9+cet+%C3%A9pisode+ainsi+que+le+c%C3%A9l%C3%A8bre+%E2%80%9CThe+long+night%E2%80%9D+%28GoT+S08E03%29%2C+aucune+surprise+pour+moi+du+coup+%21+%28https%3A%2F%2Fjp.caruana.fr%2Fnotes%2F2022%2F10%2F04%2Fgkpluginbaby-c-est-miguel%2F%29 {}
W 2022-10-04 07:10:40.669893+00:00 Error 401, response body: '{"request":"\\/1.1\\/statuses\\/[update.json](http://update.json/)","error":"Read-only application cannot POST."}'
W 2022-10-04 07:10:40.670280+00:00 Disabling source due to: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/workspace/[publish.py](http://publish.py/)", line 247, in _run
    result = self.attempt_single_item(item)
  File "/workspace/[publish.py](http://publish.py/)", line 406, in attempt_single_item
    result = [self.source](http://self.source/).gr_source.create(
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py](http://google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py)", line 662, in create
    return self._create(obj, preview=False, include_link=include_link,
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py](http://google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py)", line 873, in _create
    resp = [self.urlopen](http://self.urlopen/)(API_POST_TWEET, data=[urllib.parse.urlencode](http://urllib.parse.urlencode/)(sorted(data)))
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py](http://google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py)", line 1112, in urlopen
    return request()
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py](http://google.python.pip/pip/lib/python3.9/site-packages/granary/twitter.py)", line 1090, in request
    resp = twitter_auth.signed_urlopen(
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/twitter_auth.py](http://google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/twitter_auth.py)", line 59, in signed_urlopen
    return [util.urlopen](http://util.urlopen/)([urllib.request.Request](http://urllib.request.request/)(url, headers=headers, **kwargs))
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/webutil/util.py](http://google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/webutil/util.py)", line 1547, in urlopen
    return [urllib.request.urlopen](http://urllib.request.urlopen/)(req, *args, **kwargs)
  File "/opt/python3.9/lib/python3.9/urllib/[request.py](http://request.py/)", line 214, in urlopen
    return [opener.open](http://opener.open/)(url, data, timeout)
  File "/opt/python3.9/lib/python3.9/urllib/[request.py](http://request.py/)", line 523, in open
    response = meth(req, response)
  File "/opt/python3.9/lib/python3.9/urllib/[request.py](http://request.py/)", line 632, in http_response
    response = [self.parent.error](http://self.parent.error/)(
  File "/opt/python3.9/lib/python3.9/urllib/[request.py](http://request.py/)", line 561, in error
    return self._call_chain(*args)
  File "/opt/python3.9/lib/python3.9/urllib/[request.py](http://request.py/)", line 494, in _call_chain
    result = func(*args)
  File "/opt/python3.9/lib/python3.9/urllib/[request.py](http://request.py/)", line 641, in http_error_default
    raise HTTPError(req.full_url, code, ... hdrs, fp)
[urllib.error.HTTPError](http://urllib.error.httperror/): HTTP Error 401: Unauthorized
I 2022-10-04 07:10:40.777737+00:00 publish: Error: {"request":"\/1.1\/statuses\/[update.json](http://update.json/)","error":"Read-only application cannot POST."} HTTP Error 401: Unauthorized
I 2022-10-04 07:10:40.961246+00:00 Returning 400: {'error': 'Error: {"request":"\\/1.1\\/statuses\\/[update.json](http://update.json/)","error":"Read-only application cannot POST."} HTTP Error 401: Unauthorized'} {'response': <Response 152 bytes [200 OK]>}
E 2022-10-04 07:10:40.961750+00:00 <class '[werkzeug.exceptions.BadRequest](http://werkzeug.exceptions.badrequest/)'>: 400 Bad Request: {'error': 'Error: {"request":"\\/1.1\\/statuses\\/[update.json](http://update.json/)","error":"Read-only application cannot POST."} HTTP Error 401: Unauthorized'}
```

What can I do to (try to re)publish this item?

Thank you

**Comment by jpcaruana** [comment]
This workerd very fine, thank you. I suspect an issue on Twitter's side by disabling publish right for my token.
