### ISSUE TITLE
blogger signup breaks when author url isn't blogger profile

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#147]
looks pretty common. :/

examples: https://console.developers.google.com/project/apps~brid-gy/appengine/logs?src=acinvite&versionId=3&moduleId=default&timezone=America%2FLos_Angeles&expandAll=false&filters=status:5\d\d&filters=path:%2Fblogger%2Fstart

```
Couldn't parse author URI https://plus.google.com/102103996760244255978 , using entire URI as id
'NoneType' object has no attribute 'group' Traceback (most recent call last):
...
File "/base/data/home/apps/s~brid-gy/3.376003109405427558/activitystreams/oauth_dropins/blogger_v2.py", line 170, in get
  blog_ids.append(blog.get_blog_id())
File "/base/data/home/apps/s~brid-gy/3.376003109405427558/activitystreams/oauth_dropins/gdata-python-client/src/gdata/blogger/data.py", line 62, in get_blog_id
  return BLOG_ID2_PATTERN.match(self.id.text).group(2)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by snarfed** [comment]
seeing this again:

```
E 2015-07-20 21:02:03.670  500     225 B    78ms I 21:02:03.605 I 21:02:03.605 W 21:02:03.666 E 21:02:03.666 /blogger/start
66.26.7.89 - Christopherreid1975 [20/Jul/2015:21:02:03 -0700] "GET /blogger/start HTTP/1.1" 500 225 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:39.0) Gecko/20100101 Firefox/39.0" "www.brid.gy" ms=78 cpu_ms=8 cpm_usd=0.000114 instance=00c61b117c692ea18e67002dc3e67f44c5b60e74 app_engine_release=1.9.24
make: Got type <class 'google.appengine.api.datastore_types.Blob'>
validate: Got type <class 'oauth2client.client.OAuth2Credentials'>
Couldn't parse https://plus.google.com/117646769292953499714 , using entire value as id
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/local/lib/python2.7/site-packages/oauth_dropins/googleplus.py", line 117, in handle_exception
    return webutil_handlers.handle_exception(self, e, debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/local/lib/python2.7/site-packages/oauth2client/appengine.py", line 731, in check_oauth
    resp = method(request_handler, *args, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/local/lib/python2.7/site-packages/oauth_dropins/blogger_v2.py", line 183, in get
    blog_ids.append(blog.get_blog_id() or blog.get_blog_name())
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/local/lib/python2.7/site-packages/gdata/blogger/data.py", line 62, in get_blog_id
    return BLOG_ID2_PATTERN.match(self.id.text).group(2)
AttributeError: 'NoneType' object has no attribute 'group'
```
