### ISSUE TITLE
handle 400s from Facebook API when user has deleted their account

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#210]
[Krijn Soeteman](https://www.brid.gy/facebook/664417817) did this recently, and we [didn't handle the 400s well](https://www.brid.gy/log?start_time=1404078538&key=aglzfmJyaWQtZ3lyGwsSDEZhY2Vib29rUGFnZSIJNjY0NDE3ODE3DA): we immediately inserted a new poll task instead of backing off. not so good.

ideally we should detect deleted accounts and disable the source entity. at minimum, we should back off on 400s.

```
Fetching https://graph.facebook.com/me/posts?offset=0&limit=50&access_token=... kwargs {'headers': {'If-None-Match': u'"54d43ee9edd97f4fb1fc4e8520b407baa5267ab3"'}}
HTTP Error 400: Bad Request
Traceback (most recent call last):
...
File "/tasks.py", line 133, in do_post cache=memcache)
File "/facebook.py", line 98, in get_activities_response resp = self.as_source.get_activities_response(group_id=SELF, **kwargs)
File "/activitystreams/facebook.py", line 212, in get_activities_response resp = self.urlopen(url, headers=headers)
File "/activitystreams/facebook.py", line 380, in urlopen timeout=appengine_config.HTTP_TIMEOUT)
File ".../python2.7/urllib2.py", line 127, in urlopen return _opener.open(url, data, timeout)
...
HTTPError: HTTP Error 400: Bad Request
```

**Comment by snarfed** [comment]
[Facebook support is dead](https://brid.gy/about#rip-facebook) (#817, #826), so I'm closing this as obsolete. feel free to reopen if you have any concerns!
