### ISSUE TITLE
handle urls longer than 500 chars

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#273]
target urls are stored in the datastore as string properties, [so they're limited to 500 chars](https://developers.google.com/appengine/docs/python/ndb/properties#types). we hit our first over this limit today. (what an honor!) [here's the poll log](https://console.developers.google.com/project/apps~brid-gy/appengine/logs?filters=regex:Indexed%20value%20unsent).

the url is http://bit.ly/YXEbF8, which resolves to [http://www.wunderground.com/wundermap/?lat=37.09008&lon=-93.81924&zoom=5&...](http://www.wunderground.com/wundermap/?lat=37.09008&lon=-93.81924&zoom=5&type=terrain&date=2014-04-27&time=19:00&units=english&tl.play=0&tl.spd=2&tl.dur=2930&tl.mode=advanced&groupSevere=1&groupHurricane=1&groupFire=1&groupCamsPhotos=1&groupRealEstate=1&eyedropper=0&drought=0&extremes=0&fault=0&favs=0&femaflood=0&fire=0&firewfas=0&fissures=0&fronts=0&hurrevac=0&hur=0&labels=0&lightning=0&livesurge=0&mm=0&ndfd=0&rad=1&rad.num=1&rad.spd=25&rad.opa=81&rad.type=00Q&rad.type2=&rad.smo=1&rad.noc=1&rad.stm=0&dir=1&dir.mode=driving&sst=0&sat=0&seismicrisk=0&svr=0&ski=0&snowfall=0&stateLines=0&stormreports=0&tor=0&tfk=0&tsunami=0&riv=0&wxsn=0&cams=0&pix=0&PrecipStart=0&favs=0&cm_ven=gp082714-4)

options:
* automatically fail URLs >500 chars. not ideal, since they're valid URLs.
* write a [custom property class](https://developers.google.com/appengine/docs/python/ndb/subclassprop) to store a different indexed value
* store long URLs in parallel TextProperties

**Comment by snarfed** [comment]
reopening, this didn't seem to work for [this response](https://appengine.google.com/datastore/edit?app_id=s~brid-gy&key=aglzfmJyaWQtZ3lyawsSCFJlc3BvbnNlIl10YWc6cGx1cy5nb29nbGUuY29tLDIwMTM6ejEyZ2g1a3p1cHFyeHYxajMwNGNlNXQ1bHhmeHpoNW9nd3cwa19saWtlZF9ieV8xMDk2MDgwODAzNjQ3NTYwMjMzNTMM). the URL is http://bit.ly/IUHFAo , which redirects to this 1253 char long URL: `http://lov.okfn.org/endpoint/lov?query=PREFIX+rdf:%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23%3E%0D%0APREFIX+xsd:%3Chttp://www.w3.org/2001/XMLSchema%23%3E%0D%0APREFIX+dcterms:%3Chttp://purl.org/dc/terms/%3E%0D%0APREFIX+rdfs:%3Chttp://www.w3.org/2000/01/rdf-schema%23%3E%0D%0APREFIX+owl:%3Chttp://www.w3.org/2002/07/owl%23%3E%0D%0APREFIX+skos:%3Chttp://www.w3.org/2004/02/skos/core%23%3E%0D%0APREFIX+foaf:%3Chttp://xmlns.com/foaf/0.1/%3E%0D%0APREFIX+void:%3Chttp://rdfs.org/ns/void%23%3E%0D%0APREFIX+bibo:%3Chttp://purl.org/ontology/bibo/%3E%0D%0APREFIX+vann:%3Chttp://purl.org/vocab/vann/%3E%0D%0APREFIX+voaf:%3Chttp://purl.org/vocommons/voaf%23%3E%0D%0APREFIX+frbr:%3Chttp://purl.org/vocab/frbr/core%23%3E%0D%0APREFIX+lov:%3Chttp://lov.okfn.org/dataset/lov/lov%23%3E%0D%0APREFIX+rev:%3Chttp://purl.org/stuff/rev%23%3E%0D%0A%0D%0ASELECT+DISTINCT+%3Fperson+%3Fname+%3Fv%0D%0A%0D%0AWHERE%0D%0A%0D%0A{++++++%3Fv+a+voaf:Vocabulary.%0D%0A+++++++{%3Fv+dcterms:creator+%3Fperson}%0D%0A++++++++UNION+%0D%0A+++++++{%3Fv+dcterms:contributor+%3Fperson}.%0D%0A+++++++%3Fperson+a+foaf:Person.%0D%0A+++++++%3Fperson+foaf:name+%3Fname+%0D%0A+++++++FILTER%28contains%28str%28%3Fperson%29,%22google.com%22%29%29%0D%0A}%0D%0A+%0D%0AORDER+BY+%3Fname%0D%0A&format=HTML`.

here's where we choked:

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/3.382999756875761344/tasks.py", line 426, in send_webmentions
    self.do_send_webmentions()
  File "/base/data/home/apps/s~brid-gy/3.382999756875761344/tasks.py", line 443, in do_send_webmentions
    self.entity.unsent = sorted(unsent)
...
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1720, in _validate
    (self._name, _MAX_STRING_LENGTH))
BadValueError: Indexed value unsent must be at most 500 characters
```
