### ISSUE TITLE
char encoding bug while discovering webmention endpoint for teriiehina.net

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#315]
[log](https://www.brid.gy/log?start_time=1418245934&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo1NDI3MjY5MzQ4ODc1NDI3ODQM):

```py
Starting Response comment tag:twitter.com,2013:542726934887542784 https://twitter.com/teriiehina/status/542726934887542784
Webmention from https://brid-gy.appspot.com/comment/twitter/elfpavlik/541974355010650112/542726934887542784 to http://www.teriiehina.net/
Sending...
Starting new HTTP connection (1): www.teriiehina.net
"GET / HTTP/1.1" 200 None
Traceback (most recent call last):
 File "/base/data/home/apps/s~brid-gy/3.380705500338596153/tasks.py", line 494, in do_send_webmentions
  if not mention.send(timeout=999):
 File "/base/data/home/apps/s~brid-gy/3.380705500338596153/webmention-tools/webmentiontools/send.py", line 24, in send
  self._discoverEndpoint()
 File "/base/data/home/apps/s~brid-gy/3.380705500338596153/webmention-tools/webmentiontools/send.py", line 60, in _discoverEndpoint
  soup = BeautifulSoup(self.html)
 File "/base/data/home/apps/s~brid-gy/3.380705500338596153/activitystreams/beautifulsoup/bs4/__init__.py", line 167, in __init__
  if os.path.exists(markup):
 File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/genericpath.py", line 18, in exists
  os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)```

**Comment by kylewm** [comment]
ok it's up! git-remote-bzr makes it super easy to do the first time, not sure about subsequent updates...

**Comment by kylewm** [comment]
This should be fixed by https://github.com/snarfed/bridgy/commit/5ef37ad6df147e09cef7d9157ce612aeec51d879

**Comment by snarfed** [comment]
awesome! nice work, especially for including the test. serious brownie points for that. thank you!

want to push this? I won't touch prod the rest of the day, so all clear if you want.
