### ISSUE TITLE
500 Error when polling Facebook

### ISSUE THREAD

**Issue by jpreardon** [snarfed/bridgy#356]
I'm getting an internal server error when polling Facebook. Here's the log for reference:

<pre>0.1.0.2 - - [28/Jan/2015:06:48:58 -0800] "POST /_ah/queue/poll HTTP/1.1" 500 176 "https://www.brid.gy/poll-now" "AppEngine-Google; (+http://code.google.com/appengine)"

...

2015-01-28 14:48:58.323600 I Fetching https://graph.facebook.com/v2.2/me/posts?offset=0&limit=50&access_token=... kwargs {'headers': {}}
2015-01-28 14:48:58.749300 W Error 500, response body: Internal Server Error
2015-01-28 14:48:58.962210 E HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.381824953826554614/tasks.py", line 118, in post
    source_updates.update(self.poll(source))
  File "/base/data/home/apps/s~brid-gy/3.381824953826554614/tasks.py", line 170, in poll
    cache=cache)
  File "/base/data/home/apps/s~brid-gy/3.381824953826554614/facebook.py", line 104, in get_activities_response
    resp = self.as_source.get_activities_response(group_id=SELF, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.381824953826554614/activitystreams/facebook.py", line 227, in get_activities_response
    resp = self.urlopen(url, headers=headers, parse_response=False)
  File "/base/data/home/apps/s~brid-gy/3.381824953826554614/activitystreams/facebook.py", line 1143, in urlopen
    timeout=appengine_config.HTTP_TIMEOUT)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error</pre>

**Comment by snarfed** [comment]
hey JP! yeah, those 500s were from the Facebook API itself. all the silos' APIs return 500s occasionally; in this case, looks like it happened for your account during roughly 6:45a-8a PST, and then started working again at 9a. sorry for the trouble!
