### ISSUE TITLE
character encoding error when rendering log

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#357]
[for this log request](https://www.brid.gy/log?start_time=1422472338&key=aglzfmJyaWQtZ3lyWQsSDVB1Ymxpc2hlZFBhZ2UiMmh0dHA6Ly9kYW5pZWxpbmRxdmlzdC53aXRoa25vd24uY29tLzIwMTUvbWl0dC0yMDE0DAsSB1B1Ymxpc2gYgICAgICAgAoM):

```
Traceback (most recent call last):
  ...
  File "/base/data/home/apps/s~brid-gy/3.381842046494345440/logs.py", line 72, in get
    log.app_logs[:min(10, len(log.app_logs))]])
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 8174: invalid continuation byte
```

**Comment by snarfed** [comment]
saw this exception in a log request when running locally in dev_appserver; may be the same underlying bug or related:

```
Traceback (most recent call last):
...
  File "/Users/ryan/src/bridgy/logs.py", line 70, in get
    version_ids=['2', '3', '4', '5', '6', '7']):
...
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/logservice/logservice.py", line 491, in __iter__
    self._advance()
...
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 235, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception())
RuntimeError: UnicodeEncodeError('ascii', u'Rendered content to:\n@Anne i think it turned out ok? booking my next appt now\u2026', 77, 78, 'ordinal not in range(128)')
```

**Comment by snarfed** [comment]
looks like this is app engine's bug, not ours; the log service doesn't handle logging unicode strings well. the exception comes from inside `logservice.fetch()`; it chokes if it tries to return a log line with unicode.

app engine bugs:
* https://code.google.com/p/googleappengine/issues/detail?id=9956
* https://code.google.com/p/googleappengine/issues/detail?id=8299

**Comment by snarfed** [comment]
tentatively closing since google claims it's fixed in https://issuetracker.google.com/issues/35896206 .
