### ISSUE TITLE
superfeedr 403 subscribing to https://ashleytan.wordpress.com/feed/

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#366]
not sure why. [i've asked them on twitter.](https://twitter.com/schnarfed/status/567800120919470080) log:

```
101.127.123.12 - - [17/Feb/2015:09:10:54 -0800] "GET /wordpress/add?code=HLMlAU3b87&state=%7B%22feature%22%3A%22webmention%22%2C%22operation%22%3A%22add%22%7D HTTP/1.1" 500 ...

Updated Dr Ashley Tan (WordPress.com). <a href="http://indiewebify.me/send-webmentions/?url=https://ashleytan.wordpress.com">Try a webmention!</a> https://www.brid.gy/wordpress/ashleytan.wordpress.com
Attempting to discover webmention endpoint on https://ashleytan.wordpress.com
Starting new HTTPS connection (1): ashleytan.wordpress.com
"GET / HTTP/1.1" 200 None
No webmention endpoint found: {'code': 'NO_ENDPOINT', 'error_description': 'Unable to discover webmention endpoint.'} None
Adding Superfeedr subscription: {'hub.callback': 'https://www.brid.gy/wordpress/notify/ashleytan.wordpress.com', 'retrieve': 'true', 'hub.topic': u'https://ashleytan.wordpress.com/feed/', 'hub.mode': 'subscribe', 'format': 'json'}
Starting new HTTPS connection (1): push.superfeedr.com
"POST / HTTP/1.1" 403 None
403 Client Error: Forbidden
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/3.382293773461771064/activitystreams/oauth_dropins/wordpress_rest.py", line 167, in get
    self.finish(auth, state=self.request.get('state'))
  File "/base/data/home/apps/s~brid-gy/3.382293773461771064/wordpress_rest.py", line 213, in finish
    self.maybe_add_or_delete_source(WordPress, auth_entity, state)
  File "/base/data/home/apps/s~brid-gy/3.382293773461771064/util.py", line 350, in maybe_add_or_delete_source
    user_url=user_url, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.382293773461771064/models.py", line 372, in create_new
    superfeedr.subscribe(source, handler)
  File "/base/data/home/apps/s~brid-gy/3.382293773461771064/superfeedr.py", line 58, in subscribe
    resp.raise_for_status()
  File "/base/data/home/apps/s~brid-gy/3.382293773461771064/activitystreams/oauth_dropins/requests_module/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden
```

**Comment by snarfed** [comment]
cc'ing @julien51 and @superfeedr. thanks guys!

specifically, i saw POSTs to https://push.superfeedr.com/ with body params `{'hub.callback': 'https://www.brid.gy/wordpress/notify/ashleytan.wordpress.com', 'retrieve': 'true', 'hub.topic': u'https://ashleytan.wordpress.com/feed/', 'hub.mode': 'subscribe', 'format': 'json'}` (encoded) returned 403 a number of times yesterday, three times around 9:03am PST and three more around 9:10am PST.

**Comment by julien51** [comment]
Thanks Ryan for reporting. I checked things on our end and did indeed find in the logs a large amount of 403 responses yesterday around 9AM PST. It looks like for some reason our cache for API keys was overloaded and our behavior when that happens was not right (we should check the main database, rather than assume the key is wrong).

It's now fixed and I'm checking for more things on the cache server, to make sure this does not happen again.

Again, thanks for reporting.

**Comment by snarfed** [comment]
aha, makes sense. no problem. thanks for the explanation!
