### ISSUE TITLE
tweepy error on twitter signup

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#382]
signup url looks like `https://www.brid.gy/twitter/add?state={"feature":"listen","operation":"add"}&oauth_token=...&oauth_verifier=...`

exception is:
```py
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.383347921635681683/activitystreams/oauth_dropins/twitter.py", line 185, in get
    access_token_key, access_token_secret = auth.get_access_token(oauth_verifier)
  File "/base/data/home/apps/s~brid-gy/3.383347921635681683/activitystreams/oauth_dropins/tweepy_module/tweepy/auth.py", line 94, in get_access_token
    raise TweepError(e)
TweepError: Not a valid urlencoded string.
```

**Comment by snarfed** [comment]
may be transient. this was for https://www.brid.gy/twitter/ballombert ; he signed up successfully (twice!) just a minute after this error.
