### ISSUE TITLE
response changed false positive for FB tagged people

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#384]
The message_tags field is slightly different when fetching a comment directly:

```
{
  "id": "10101224606525629_10101224916514409",
  "from": {
    "id": "12802152",
    "name": "Kyle Mahan"
  },
  "message": "Bethany oh god i can just hear him using pseudosciencey jargon to try and explain it",
  "message_tags": [
    {
      "id": "10152546220062658",
      "name": "Bethany",
      "type": "user",
      "offset": 0,
      "length": 7
    }
  ],
  "can_remove": true,
  "created_time": "2015-02-27T16:34:46+0000",
  "like_count": 1,
  "user_likes": false
}
```

vs. fetching it as part of its parent post

```
      {
        "id": "10101224606525629_10101224916514409",
        "can_remove": true,
        "created_time": "2015-02-27T16:34:46+0000",
        "from": {
          "id": "12802152",
          "name": "Kyle Mahan"
        },
        "like_count": 1,
        "message": "Bethany oh god i can just hear him using pseudosciencey jargon to try and explain it",
        "message_tags": [
          {
            "id": "10152546220062658",
            "length": 7,
            "name": "Bethany Kingsley",
            "offset": 0,
            "type": "user"
          }
        ],
        "user_likes": false
      },
```

in [activity_changed](https://github.com/snarfed/activitystreams-unofficial/blob/master/source.py#L528), we should probably recurse into the complex objects like "tags" and "attachments" to only check certain fields.

**Comment by snarfed** [comment]
thanks for debugging and filing!

**Comment by snarfed** [comment]
oh man, hilarious symptom of this: we don't use the `Response.old_response_jsons` field right now - it's just used as a record - but we let it grow without bound, so we eventually hit the [1MB datastore entity limit](https://cloud.google.com/appengine/docs/python/ndb/#quotas). e.g. [this poll log](https://brid-gy.appspot.com/log?start_time=1428621194&key=aglzfmJyaWQtZ3lyGAsSDEZhY2Vib29rUGFnZSIGMjEyMDM4DA) and [this Response entity](https://appengine.google.com/datastore/edit?app_id=s~brid-gy&version_id=3.383403806568631284&key=aglzfmJyaWQtZ3lyRwsSCFJlc3BvbnNlIjl0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxMDEzOTg0MDAzMDYzNzNfMTAxMDEzOTg0NzgzMjUwMjMM):

```py
Response changed! Re-propagating. Original: Response(key=Key('Response', 'tag:facebook.com,2013:10101398400306373_10101398478325023'), ... (length 1000000)
suspended generator _put_tasklet(context.py:343) raised RequestTooLargeError(The request to API call datastore_v3.Put() was too large.)
suspended generator put(context.py:810) raised RequestTooLargeError(The request to API call datastore_v3.Put() was too large.)
suspended generator transaction(context.py:1003) raised RequestTooLargeError(The request to API call datastore_v3.Put() was too large.)
The request to API call datastore_v3.Put() was too large.
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/3.383403806568631284/tasks.py", line 109, in post
    source_updates.update(self.poll(source))
  File "/base/data/home/apps/s~brid-gy/3.383403806568631284/tasks.py", line 295, in poll
    resp.get_or_save(source)
...
  File "/base/data/home/apps/s~brid-gy/3.383403806568631284/models.py", line 622, in get_or_save
    resp.put()
  File "/base/data/home/apps/s~brid-gy/3.383403806568631284/activitystreams/oauth_dropins/webutil/models.py", line 18, in put
    return super(StringIdModel, self).put(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 3384, in _put
    return self._put_async(**ctx_options).get_result()
...
      RequestTooLargeError: The request to API call datastore_v3.Put() was too large.
```

simple fix is to cap `old_response_jsons` to a certain length or size (in bytes), especially since we don't use it at all.

**Comment by snarfed** [comment]
both current uses of `activity_changed()` use it to compare responses, not activities, so i'm just going to drop the `tags` and `attachments` comparisons entirely.
