### ISSUE TITLE
handle non-UTF-8 HTML pages

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#385]
we're assuming UTF-8 somewhere in publish, and choking when we get a page in a different charset, e.g. http://wirres.net/article/articleview/7573/1/6/ which is `Content-Type: text/html
` and has `<meta charset="iso-8859-1"/>`. [log](https://www.brid.gy/log?start_time=1428844598&key=aglzfmJyaWQtZ3lyVgsSDVB1Ymxpc2hlZFBhZ2UiL2h0dHA6Ly93aXJyZXMubmV0L2FydGljbGUvYXJ0aWNsZXZpZXcvNzU3My8xLzYvDAsSB1B1Ymxpc2gYgICAgIDyiAoM):

```py
I Params: [(u'source', u'http://wirres.net/article/articleview/7573/1/6/'), (u'target', u'http://brid.gy/publish/twitter'), (u'bridgy_omit_link', u'false'), (u'source_key', u'aglzfmJy...')]
I Source: https://www.brid.gy/twitter/diplix , features [u'publish', u'listen'], status enabled
D Publish entity: aglzfmJyaWQtZ3lyVgsSDVB1Ymxpc2hlZFBhZ2UiL2h0dHA6Ly93aXJyZXMubmV0L2FydGljbGUvYXJ0aWNsZXZpZXcvNzU3My8xLzYvDAsSB1B1Ymxpc2gYgICAgIDyiAoM
I Starting new HTTP connection (1): wirres.net
D "GET /article/articleview/7573/1/6/ HTTP/1.1" 200 None
E Expected valid UTF-8, got '<!doctype html>\n \n<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="de-1996"> <![endif]-->\n<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="de-1996"> <![endif]-->\n<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="de-1996"> <![endif]-->\n \n<!--[if gt IE 8]><!--> <html class="no-js" lang="de-1996"> <!--<![endif]-->\n<head>\n<meta charset="iso-8859-1"/>\n ...(length 71509)
```

**Comment by snarfed** [comment]
aha, the exception happens when we try to store it in the datastore, which [requires Unicode for `TextProperty`](https://cloud.google.com/appengine/docs/python/ndb/properties#types). i could switch to `BlobProperty`, but i'd really rather not.

```py
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/3.383498254578038417/publish.py", line 448, in post
    result = self._run()
  File "/base/data/home/apps/s~brid-gy/3.383498254578038417/publish.py", line 177, in _run
    resp = self.fetch_mf2(url)
  File "/base/data/home/apps/s~brid-gy/3.383498254578038417/webmention.py", line 75, in fetch_mf2
    self.entity.html = text
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1364, in __set__
    self._set_value(entity, value)
...
BadValueError: Expected valid UTF-8, got ...
```
