### ISSUE TITLE
upgrading requests to urllib3 makes propagates fail with IncompleteRead

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#396]
as part of #389, i tried upgrading tweepy to 3.3 (snarfed/oauth_dropins@68e6ea944f3e4fd22bbde54fb285aa052c1222a1), which included upgrading python-requests to 2.6.2 which uses urllib3 instead of httplib2. that made propagate tasks start failing with `IncompleteRead`s, probably due to a mismatch in handling for chunked requests (`Transfer-Encoding: chunked`). not sure how to fix this quite yet.

[example log](https://www.brid.gy/log?start_time=1430169921&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo1OTI3OTYyMTczOTYwNzY1NDYM):
```py
Starting Response repost tag:twitter.com,2013:592796217396076546 https://twitter.com/svaroschi/status/592796217396076546
Webmention from https://brid-gy.appspot.com/repost/twitter/mathewi/592795567140536323/592796217396076546 to http://www.mathewingram.com/work/2015/04/27/eu-publishers-sign-deal-with-google-but-are-they-focusing-on-the-right-enemy/
Sending...
Starting new HTTP connection (1): www.mathewingram.com
"GET /work/2015/04/27/eu-publishers-sign-deal-with-google-but-are-they-focusing-on-the-right-enemy/ HTTP/1.1" 200 None

Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/3.383902397363262415/tasks.py", line 478, in do_send_webmentions
    if not mention.send(timeout=999, headers=util.USER_AGENT_HEADER):
  File "/base/data/home/apps/s~brid-gy/3.383902397363262415/webmention-tools/webmentiontools/send.py", line 24, in send
    self._discoverEndpoint()
  File "/base/data/home/apps/s~brid-gy/3.383902397363262415/webmention-tools/webmentiontools/send.py", line 30, in _discoverEndpoint
    r = requests.get(self.target_url, verify=False, **self.requests_kwargs)
...
  File "/base/data/home/apps/s~brid-gy/3.383902397363262415/activitystreams/oauth_dropins/requests_module/requests/packages/urllib3/response.py", line 304, in stream
    for line in self.read_chunked(amt):
  File "/base/data/home/apps/s~brid-gy/3.383902397363262415/activitystreams/oauth_dropins/requests_module/requests/packages/urllib3/response.py", line 411, in read_chunked
    raise httplib.IncompleteRead(''.join(line))
IncompleteRead: IncompleteRead(16 bytes read)
Error sending to endpoint: {'code': 'EXCEPTION'}
```

**Comment by shazow** [comment]
Keep an eye on https://github.com/shazow/urllib3/issues/618

**Comment by ludoch** [comment]
Looking....

**Comment by snarfed** [comment]
tried the latest version of requests (2.8.1) just now, but no luck, at least in dev_appserver. traceback below.

2.8.1 was released after those commits, but they're evidently not merged into requests, and it's unclear if they will be. (i also tried installing the latest urllib3 (1.12) manually, but i expect requests still used the version it bundles.)

ah well. i'll try again in a while!

```
Traceback (most recent call last):
...
  File "/Users/ryan/src/bridgy/twitter.py", line 134, in post
    return self.start_oauth_flow(util.get_required_param(self, 'feature'))
  File "/Users/ryan/src/bridgy/twitter.py", line 106, in start_oauth_flow
    return handler.post()
  File "/Users/ryan/src/bridgy/local/lib/python2.7/site-packages/oauth_dropins/handlers.py", line 101, in post
    url = self.redirect_url(state=self.request.get('state'))
  File "/Users/ryan/src/bridgy/util.py", line 512, in redirect_url
    self.construct_state_param_for_add(state, **kwargs))
  File "/Users/ryan/src/bridgy/local/lib/python2.7/site-packages/oauth_dropins/twitter.py", line 145, in redirect_url
    signin_with_twitter=not self.access_type, access_type=self.access_type)
  File "/Users/ryan/src/bridgy/local/lib/python2.7/site-packages/tweepy/auth.py", line 85, in get_authorization_url
    self.request_token = self._get_request_token(access_type=access_type)
  File "/Users/ryan/src/bridgy/local/lib/python2.7/site-packages/tweepy/auth.py", line 68, in _get_request_token
    raise TweepError(e)
TweepError: ('Connection aborted.', error(13, 'Permission denied'))
```

**Comment by snarfed** [comment]
http://stackoverflow.com/a/35944044/186123 told me requests 2.10.0 + requests-toolbelt works...and it does! yay!

**Comment by snarfed** [comment]
reopening until we figure out sigmavirus24/requests-toolbelt#141.

**Comment by snarfed** [comment]
yay, done!
