### ISSUE TITLE
twitter poll crash: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#408]
no clue what happened here. from [this log](https://www.brid.gy/log?start_time=1431992372&key=aglzfmJyaWQtZ3lyFgsSB1R3aXR0ZXIiCWRhdmlkbWVhZAw):

```py
Traceback (most recent call last):
  ...
  File "/base/data/home/apps/s~brid-gy/3.384275116935974597/tasks.py", line 109, in post
    source_updates.update(self.poll(source))
  File "/base/data/home/apps/s~brid-gy/3.384275116935974597/tasks.py", line 161, in poll
    cache=cache)
  File "/base/data/home/apps/s~brid-gy/3.384275116935974597/models.py", line 222, in get_activities_response
    return self.as_source.get_activities_response(group_id=as_source.SELF, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.384275116935974597/activitystreams/twitter.py", line 211, in get_activities_response
    activities += [self._make_like(tweet, user) for tweet in liked]
  File "/base/data/home/apps/s~brid-gy/3.384275116935974597/activitystreams/twitter.py", line 1068, in _make_like
    tweet_id = tweet.get('id_str')
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by snarfed** [comment]
this only happened once; i'm guessing twitter returned an unusual error response with a single string message instead of a JSON object. wontfix.
