### ISSUE TITLE
poll crash: 'NoneType' object has no attribute 'status'

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#410]
poll for [Unofficial: Farting](https://www.brid.gy/facebook/1593105984281620) (FB; lolol; cc @kylewm) failed 8 times btw ~12:45pm and 2pm PST today. here are successful logs for polls [before](https://brid-gy.appspot.com/log?start_time=1432237640&key=aglzfmJyaWQtZ3lyKQsSDkdvb2dsZVBsdXNQYWdlIhUxMTUwMzE3NzQ5OTY2NDA4MzQ4MTIM) and [after](https://www.brid.gy/log?start_time=1432242291&key=aglzfmJyaWQtZ3lyIgsSDEZhY2Vib29rUGFnZSIQMTU5MzEwNTk4NDI4MTYyMAw). example failing log is below. no idea what actually happened yet.

```py
Fetching https://graph.facebook.com/v2.2/me/posts?offset=0&limit=50&access_token=CAAD..., kwargs {'headers': {'If-None-Match': u'"dcf0a2fe4f87651e9deb399561daa844f6b7c51c"'}}
Error 500, response body: Internal Server Error
suspended generator transaction(context.py:1004) raised AttributeError('NoneType' object has no attribute 'status')
'NoneType' object has no attribute 'status'
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/3.384450004523261815/tasks.py", line 120, in post
    source = self.update_source(source, source_updates)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/utils.py", line 179, in inner_wrapper
    return wrapped_decorator(func, args, kwds, **options)
...
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 3786, in <lambda>
    return transaction_async(lambda: func(*args, **kwds), **options)
  File "/base/data/home/apps/s~brid-gy/3.384450004523261815/tasks.py", line 136, in update_source
    setattr(source, name, val)
AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by snarfed** [comment]
caused by deleting the source entity from the datastore manually. :P wontfix!
