### ISSUE TITLE
odd broken twitter publish attempt

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#414]
this is weird. yesterday morning around 2:30AM PST we had a strange failed twitter publish attempt.

1. we got a GET to `/twitter/publish/start` that successfully generated an OAuth request and redirected to twitter for approval
1.  they approved and got redirected back to `/publish/twitter/finish`
1. that request had no state param, so it failed there.

request logs below, [and here](https://console.developers.google.com/project/brid-gy/logs?service=appengine.googleapis.com&key1=default&key2=3&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=America%2FLos_Angeles&filters=text:AhyH0Fvm).

mysteries:
* it should have been a POST to `/twitter/publish/start` not a GET. the only place in the codebase that points there is the form in [templates/preview.html](https://github.com/snarfed/bridgy/blob/master/templates/preview.html#L16), which has `method="post"`
* [the logs don't show a preview attempt beforehand at all.](https://console.developers.google.com/project/brid-gy/logs?service=appengine.googleapis.com&key1=default&key2=3&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=America%2FLos_Angeles&filters=text:%2Fpublish%2Fpreview)
* who was this? the logs don't have anything identifying, just oauth codes and tokens. :/ the client ip is  84.255.226.221, which is t-2.net, a Slovenian ISP. the request pattern and user agent suggest that it was a human, not a bot.

`/twitter/publish/start` log (all from oauth-dropins and tweepy):
```
Collected params: [(u'oauth_nonce', u'...'), (u'oauth_timestamp', u'1433064494'), (u'oauth_consumer_key', u'...'), (u'oauth_signature_method', u'HMAC-SHA1'), (u'oauth_version', u'1.0'), (u'oauth_callback', u'https://www.brid.gy/publish/twitter/finish')]
Normalized params: oauth_callback=https%3A%2F%2Fwww.brid.gy%2Fpublish%2Ftwitter%2Ffinish&oauth_consumer_key=...&oauth_nonce=...&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1433064494&oauth_version=1.0
Normalized URI: https://api.twitter.com/oauth/request_token
Base signing string: POST&https%3A%2F%2Fapi.twitter.com%2Foauth%2Frequest_token&oauth_callback%3Dhttps%253A%252F%252Fwww.brid.gy%252Fpublish%252Ftwitter%252Ffinish%26oauth_consumer_key%3...%26oauth_nonce%3D...%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1433064494%26oauth_version%3D1.0
Signature: ...
Encoding URI, headers and body to utf-8.
Starting new HTTPS connection (1): api.twitter.com
"POST /oauth/request_token HTTP/1.1" 200 None
Generated request token, redirecting to Twitter: https://api.twitter.com/oauth/authenticate?oauth_token=...
Starting OAuth flow: redirecting to https://api.twitter.com/oauth/authenticate?oauth_token=...
```

`/publish/twitter/finish` log (almost all from oauth-dropins and tweepy):
```
Collected params: [(u'oauth_nonce', u'...'), (u'oauth_timestamp', u'1433064497'), (u'oauth_verifier', u'...'), (u'oauth_consumer_key', u'...'), (u'oauth_signature_method', u'HMAC-SHA1'), (u'oauth_version', u'1.0'), (u'oauth_token', u'...')]
Normalized params: oauth_consumer_key=...&oauth_nonce=...&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1433064497&oauth_token=...&oauth_verifier=...&oauth_version=1.0
Normalized URI: https://api.twitter.com/oauth/access_token
Base signing string: POST&https%3A%2F%2Fapi.twitter.com%2Foauth%2Faccess_token&oauth_consumer_key%3D...%26oauth_nonce%3D...%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1433064497%26oauth_token%3D...%26oauth_verifier%3D...%26oauth_version%3D1.0
Signature: ...
Encoding URI, headers and body to utf-8.
Starting new HTTPS connection (1): api.twitter.com
"POST /oauth/access_token HTTP/1.1" 200 None
Collected params: [(u'oauth_nonce', u'...'), (u'oauth_timestamp', u'1433064497'), (u'oauth_consumer_key', u'...'), (u'oauth_signature_method', u'HMAC-SHA1'), (u'oauth_version', u'1.0'), (u'oauth_token', u'...')]
Normalized params: oauth_consumer_key=...&oauth_nonce=...&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1433064497&oauth_token=...&oauth_version=1.0
Normalized URI: https://api.twitter.com/1.1/account/verify_credentials.json
Base signing string: GET&https%3A%2F%2Fapi.twitter.com%2F1.1%2Faccount%2Fverify_credentials.json&oauth_consumer_key%3D...%26oauth_nonce%3D...%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1433064497%26oauth_token%3D...%26oauth_version%3D1.0
Signature: ...
Encoding URI, headers and body to utf-8.
Generated Authorization header from access token key ... and secret ...
Fetching https://api.twitter.com/1.1/account/verify_credentials.json
decoding state ""
Traceback (most recent call last):
...
File "/base/data/home/apps/s~brid-gy/3.384519463642808388/activitystreams/oauth_dropins/twitter.py", line 98, in handle_exception
    return webutil_handlers.handle_exception(self, e, debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.384519463642808388/activitystreams/oauth_dropins/twitter.py", line 196, in get
    self.finish(auth, state=self.request.get('state'))
  File "/base/data/home/apps/s~brid-gy/3.384519463642808388/publish.py", line 483, in finish
    source = ndb.Key(urlsafe=self.state['source_key']).get()
KeyError: 'source_key'
```

**Comment by snarfed** [comment]
(i'm not really prioritizing this right now.)

**Comment by kylewm** [comment]
well, we know someone in Slovenia right now... @rhiaro!

**Comment by rhiaro** [comment]
Hmm, I don't think that was me. I don't have any code that talks to bridgy at the moment, I just use bridgy publish manually, and I'm pretty sure I was asleep then.

**Comment by kylewm** [comment]
Darn, thanks for checking. Thought I was being very clever. :)

**Comment by snarfed** [comment]
no news or recurrence; closing.
