### ISSUE TITLE
Flickr publish support

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#432]
Flickr has a pretty good API, and it's one of the older more well-established photo silos, so it would be a natural place to POSSE to.

Would be nice to be able to automatically create a Flickr POSSE copy photo/video/comment/favorite from indie photo/video posts, Flickr comment from indie reply posts that were in-reply-to a Flickr photo/video, and Flickr favorites from indie likes of Flickr posts.

Specifically:
* photo -> Flickr photo
* video -> Flickr video
* reply in-reply-to a Flickr post -> Flickr comment on that post
* like of a Flickr post -> Flickr favorite on that post

See also related: issue #225

**Comment by kylewm** [comment]
launched this just now and tried a few tests, everything is tickety-boo so far!

https://kylewm.com/2015/11/at-some-henry-miller-thing-not-that-henry-miller-1 &rarr; ttps://www.flickr.com/photos/kindofblue115/22637613438/

and 

https://kylewm.com/2015/11/attempting-to-posse-a-comment-to-flickr &rarr; https://www.flickr.com/photos/kindofblue115/22637613438/#comment72157661275088921

I can't actually close this issue until I add it to the docs though :(

**Comment by snarfed** [comment]
wow, that's awesome, congratulations! so fast too. thank you! and you may still beat me on FB person tagging since it's not in the docs either :P

**Comment by kylewm** [comment]
@tantek ran into an error posting a Instagram photo to Flickr. Maybe, hopefully, transient?

```
2015-11-16 07:14:40.771280 D publishing object type note to Flickr
2015-11-16 07:14:45.788970 W Error: Deadline exceeded while waiting for HTTP response from URL: https://scontent-lax3-1.cdninstagram.com/hphotos-xpt1/t51.2885-15/e35/12237292_1642476692689000_1811828067_n.jpg
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/7.388602505191055114/publish.py", line 210, in _run
result = self.attempt_single_item(item)
File "/base/data/home/apps/s~brid-gy/7.388602505191055114/publish.py", line 333, in attempt_single_item
result = self.source.gr_source.create(obj, include_link=not omit_link)
File "/base/data/home/apps/s~brid-gy/7.388602505191055114/local/lib/python2.7/site-packages/granary/flickr.py", line 90, in create
return self._create(obj, preview=False, include_link=include_link)
File "/base/data/home/apps/s~brid-gy/7.388602505191055114/local/lib/python2.7/site-packages/granary/flickr.py", line 156, in _create
resp = self.upload_photo(params, urllib2.urlopen(image_url))
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 127, in urlopen
return _opener.open(url, data, timeout)
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 404, in open
response = self._open(req, data)
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 422, in _open
'_open', req)
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 382, in _call_chain
result = func(*args)
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 1222, in https_open
return self.do_open(httplib.HTTPSConnection, req)
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 1187, in do_open
r = h.getresponse(buffering=True)
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 526, in getresponse
raise HTTPException(str(e))
HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://scontent-lax3-1.cdninstagram.com/hphotos-xpt1/t51.2885-15/e35/12237292_1642476692689000_1811828067_n.jpg
```

**Comment by kylewm** [comment]
thanks @snarfed and thanks for reviewing right away :pray:

**Comment by snarfed** [comment]
this is done, right? yay! tentatively closing.
