### ISSUE TITLE
Twitter / 500 Internal server error

### ISSUE THREAD

**Issue by tinokremer** [snarfed/bridgy#439]
I think there is a generic issue with network connectivity or with bridgy itself, but when I click on the Twitter button to get started this is shown:

500 Internal Server Error

The server has either erred or is incapable of performing the requested operation.

URL: https://www.brid.gy/twitter/start

Having said that, this is one of the logs for Facebook. It seems there are issues connecting with my instance (working fine from here, but I'm in The Netherlands and withknown.com is in Amazon's cloud it seems):

0.1.0.2 - - [08/Aug/2015:05:39:59 -0700] "POST /_ah/queue/propagate HTTP/1.1" 304 133 "http://www.brid.gy/_ah/queue/poll" "AppEngine-Google; (+http://code.google.com/appengine)"

2015-08-08 12:39:56.154020 D Params: UnicodeMultiDict([(u'response_key', u'aglzfmJy...')])
2015-08-08 12:39:56.199990 I Source: Tino Kremer (Facebook) 403320719840728, http://brid-gy.appspot.com/facebook/403320719840728
2015-08-08 12:39:56.200260 I Created by this poll: http://brid-gy.appspot.com/log?start_time=1439019090&key=aglzfmJyaWQtZ3lyIQsSDEZhY2Vib29rUGFnZSIPNDAzMzIwNzE5ODQwNzI4DA
2015-08-08 12:39:56.200460 I Starting Response comment tag:facebook.com,2013:451491091690357_451621741677292 https://www.facebook.com/451491091690357?comment_id=451621741677292
2015-08-08 12:39:56.209260 I Starting new HTTPS connection (1): tinokremer.withknown.com
2015-08-08 12:39:56.265130 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.322119 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.376190 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.432120 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.488290 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.544300 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.601130 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.656430 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.710589 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.767339 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.824280 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.881260 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.937320 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:56.991329 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.094540 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.148930 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.202780 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.266680 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.320570 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.378060 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.435869 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.489609 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.545599 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.603440 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.657520 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.713320 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.770020 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.827390 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.884560 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.940820 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.994859 D "HEAD /2015/amsterdam HTTP/1.1" 307 None
2015-08-08 12:39:57.996020 W Couldn't resolve URL https://tinokremer.withknown.com/2015/amsterdam : Exceeded 30 redirects.
2015-08-08 12:39:57.998600 I Webmention from https://brid-gy.appspot.com/comment/facebook/403320719840728/451491091690357/451491091690357_451621741677292 to https://tinokremer.withknown.com/2015/amsterdam
2015-08-08 12:39:58.000310 I Using cached webmention endpoint for tinokremer.withknown.com: https://tinokremer.withknown.com/webmention/
2015-08-08 12:39:58.000460 I Sending...
2015-08-08 12:39:58.007670 I Starting new HTTPS connection (1): tinokremer.withknown.com
2015-08-08 12:39:58.060920 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.162750 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.217050 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.272559 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.328500 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.384190 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.439960 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.495750 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.549440 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.608300 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.665040 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.721280 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.777470 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.833780 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.890940 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:58.948240 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.008910 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.063290 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.117510 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.233310 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.293690 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.347780 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.403780 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.459940 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.514349 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.572900 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.630210 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.684050 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.739640 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.796240 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.852269 D "POST /webmention/ HTTP/1.1" 307 None
2015-08-08 12:39:59.853650 W 
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/tasks.py", line 473, in do_send_webmentions
    if not mention.send(timeout=999, headers=util.USER_AGENT_HEADER):
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/local/lib/python2.7/site-packages/webmentiontools/send.py", line 27, in send
    return self._notifyReceiver()
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/local/lib/python2.7/site-packages/webmentiontools/send.py", line 79, in _notifyReceiver
    r = requests.post(self.receiver_endpoint, verify=False, data=payload, **self.requests_kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/local/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/local/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/local/lib/python2.7/site-packages/requests/sessions.py", line 506, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/base/data/home/apps/s~brid-gy/3.386281926791272157/local/lib/python2.7/site-packages/requests/sessions.py", line 99, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
TooManyRedirects: Exceeded 30 redirects.
2015-08-08 12:39:59.854290 W Error sending to endpoint: {'code': 'EXCEPTION'}
2015-08-08 12:39:59.854460 W Propagate task failed

**Comment by snarfed** [comment]
sorry for the trouble @tinokremer, and thanks for the report! the twitter signup 500 seems like a bridgy bug; i'll look into it.

the known redirect loops on your facebook webmention seem like a possible bug or misconfiguration with known itself...? cc'ing @benwerd and @mapkyca, hopefully they might know more.

**Comment by snarfed** [comment]
@tinokremer the twitter signup 500 is fixed. apologies again. feel free to retry it!

**Comment by tinokremer** [comment]
I can confirm the 500 server error is gone. Also, did you release / retry the queue? I had lots of webmentions in the queue (obviously as it was not working at the time) and now they are all handled. I had like 20 notifications.

**Comment by snarfed** [comment]
great! yup, bridgy retries webmentions automatically for a day before giving up.
