### ISSUE TITLE
disabled FB account but didn't send FB notification

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#450]
thanks for reporting, @aaronpk! log below. looks like the root cause is that FB returned a 401 that included an `is_transient :true` in the body, so we shouldn't have disabled the account.

disappointing that they think it's ok to return "transient" 401s. sigh. oh FB, you so crazy! :sob: :gun: 

```
[12/Aug/2015:10:59:52 -0700] "POST /_ah/queue/poll HTTP/1.1" 200 ...
Params: UnicodeMultiDict([(u'last_polled', u'2015-08-12-17-49-21'), (u'source_key', u'aglzfmJyaWQtZ3lyGgsSDEZhY2Vib29rUGFnZSIIMTE1MDA0NTkM')])
Source: Aaron Parecki (Facebook) 11500459, http://brid-gy.appspot.com/facebook/11500459
Last poll: http://brid-gy.appspot.com/log?start_time=1439401761&key=aglzfmJyaWQtZ3lyGgsSDEZhY2Vib29rUGFnZSIIMTE1MDA0NTkM
Using ETag "ae1728cabbc02f9bd6de3d490aeeddd37e81bdb0", last activity id 10204832601528252
Fetching https://graph.facebook.com/v2.2/me/feed?offset=0&limit=50&access_token=CAAD..., kwargs {'headers': {'If-None-Match': u'"ae1728cabbc02f9bd6de3d490aeeddd37e81bdb0"'}}
Fetching https://graph.facebook.com/v2.2/me/photos/uploaded?access_token=CAAD..., kwargs {}
Error 401, response body: {"error":{"message":"An unexpected error has occurred. Please retry your request later.","type":"OAuthException","is_transient":true,"code":2}}
Unauthorized error: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/3.386383325163464983/tasks.py", line 161, in poll
    cache=cache)
  File "/base/data/home/apps/s~brid-gy/3.386383325163464983/facebook.py", line 119, in get_activities_response
    photos = self.get_data(API_PHOTOS)
  File "/base/data/home/apps/s~brid-gy/3.386383325163464983/facebook.py", line 101, in get_data
    return self.gr_source.urlopen(url).get('data', [])
  File "/base/data/home/apps/s~brid-gy/3.386383325163464983/local/lib/python2.7/site-packages/granary/facebook.py", line 1260, in urlopen
    timeout=appengine_config.HTTP_TIMEOUT)
...
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
Disabling source!
Added poll task 9351678035652118129 with args {'countdown': 661.27111531846674}
```

**Comment by snarfed** [comment]
https://console.cloud.google.com/errors/CIS50q7725Kh-AE?time=P1D&filter&project=brid-gy
