### ISSUE TITLE
isolated twitter signup oauth failure: 'Invalid request token'

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#451]
looks like the same person (or two) keep trying to sign up for bridgy on twitter and we keep getting this unusual 401 from twitter. requests are all from `37.203.160.152` and `2a01:388:25c:150::1:2c`; not sure which twitter user(s). log below.

```
[24/Aug/2015:16:34:38 -0700] "GET /twitter/add?state=%7B%22feature%22%3A%22listen%22%2C%22operation%22%3A%22add%22%7D&oauth_token=...&oauth_verifier=..."
Fetching token from https://api.twitter.com/oauth/access_token using client <Client nonce=None, signature_method=HMAC-SHA1, realm=None, encoding=utf-8, timestamp=None, resource_owner_secret=****, decoding=utf-8, verifier=8X6kOiGBN2UBL7OzAjFipUP8GStLHbOM, signature_type=AUTH_HEADER, rsa_key=None, resource_owner_key=Imt40gAAAAAASyT_AAABTvrXk00, client_secret=****, callback_uri=None, client_key=dgaolSZTTZfVOgUufafw>
Signing request ...
Collected params: [(u'oauth_nonce', u'...'), (u'oauth_timestamp', u'1440459278'), (u'oauth_verifier', u'...'), (u'oauth_consumer_key', u'...'), (u'oauth_signature_method', u'HMAC-SHA1'), (u'oauth_version', u'1.0'), (u'oauth_token', u'...')]
...
Starting new HTTPS connection (1): api.twitter.com
"POST /oauth/access_token HTTP/1.1" 401 None
OAuth error
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.386642018005115182/local/lib/python2.7/site-packages/oauth_dropins/twitter.py", line 186, in get
    access_token_key, access_token_secret = auth.get_access_token(oauth_verifier)
  File "/base/data/home/apps/s~brid-gy/3.386642018005115182/local/lib/python2.7/site-packages/tweepy/auth.py", line 108, in get_access_token
    raise TweepError(e)
TweepError: Token request failed with code 401, response was 'Invalid request token.'.
```

**Comment by snarfed** [comment]
kinda stumped right now on how to debug this. any ideas are welcome!

**Comment by snarfed** [comment]
looks like this isn't happening any more. last instance of it in the logs was 8/26.
