### ISSUE TITLE
fully isolate virtualenv

### ISSUE THREAD

**Issue by ckruse** [snarfed/bridgy#461]
It seems that Brid.gy doesn't support SNI itself:

~~~
 2a00:1828:2000:774::2 - - [06/Sep/2015:05:52:12 -0700] "POST /publish/webmention HTTP/1.1" 400 156 - -

2015-09-06 12:52:11.742660 I Params: [(u'source', u'https://wwwtech.de/notes/13'), (u'target', u'https://www.brid.gy/publish/twitter')]
2015-09-06 12:52:11.759079 I Source: https://www.brid.gy/twitter/cjk101010 , features [u'publish', u'listen'], status enabled
2015-09-06 12:52:11.806690 D Publish entity: aglzfmJyaWQtZ3lyQgsSDVB1Ymxpc2hlZFBhZ2UiG2h0dHBzOi8vd3d3dGVjaC5kZS9ub3Rlcy8xMwwLEgdQdWJsaXNoGICAgICArpkKDA
2015-09-06 12:52:11.838609 I Starting new HTTPS connection (1): wwwtech.de
2015-09-06 12:52:12.406580 W Could not fetch source URL https://wwwtech.de/notes/13
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/4.386948893978327072/webmention.py", line 64, in fetch_mf2
fetched = util.requests_get(url)
File "/base/data/home/apps/s~brid-gy/4.386948893978327072/util.py", line 108, in requests_get
return requests.get(url, **kwargs)
File "/base/data/home/apps/s~brid-gy/4.386948893978327072/local/lib/python2.7/site-packages/requests/api.py", line 65, in get
return request('get', url, **kwargs)
File "/base/data/home/apps/s~brid-gy/4.386948893978327072/local/lib/python2.7/site-packages/requests/api.py", line 49, in request
response = session.request(method=method, url=url, **kwargs)
File "/base/data/home/apps/s~brid-gy/4.386948893978327072/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
resp = self.send(prep, **send_kwargs)
File "/base/data/home/apps/s~brid-gy/4.386948893978327072/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/base/data/home/apps/s~brid-gy/4.386948893978327072/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
raise SSLError(e, request=request)
SSLError: hostname 'wwwtech.de' doesn't match either of 'm.jeena.net', 'jeena.net'
~~~

The host jugulator.defunced.de serves jeena.net as the default SSL vhost and WWWTech.de over SNI. Is there a way around that?

Just as a side note: only WWWTech.de has a IPv6 address. Jeena.net will get its own v6 adress in the future, so it might be a solution to prefer IPv6?

**Comment by snarfed** [comment]
thanks for filing @ckruse, and sorry for the trouble! i think we've managed to support SNI in publish in the past, but we may have reverted, or we may just need to pass the domain to requests explicitly so it knows what to verify. we've also switched requests versions a couple times, so that might be it. we'll investigate soon.

**Comment by ckruse** [comment]
Whatever you did: it works now. Thanks!

**Comment by snarfed** [comment]
ohh that's an interesting clue. i didn't do anything to fix this explicitly, but i did deploy from my environment, and your failure was on a deploy from @kylewm's environment. so evidently we still have something that's not fully specified in our setup. hrmph.

**Comment by snarfed** [comment]
renaming due to changed scope. @kylewm and i compared `pip freeze`s and we do indeed have wildly different packages (i'm left, he's right):
```
1,2c1,6
< beautifulsoup4==4.3.2
< -e git+git@github.com:snarfed/gdata-python-client-1.git@e1404ec0724a0f603dfc24841eada6d284b60f0e#egg=gdata-master
---
> (local)kmahan@lemur:~/projects/bridgy$ pip freeze
> You are using pip version 7.1.0, however version 7.1.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> beautifulsoup4==4.4.0
> docopt==0.6.2
> -e git+git@github.com:snarfed/gdata-python-client-1.git@e1404ec0724a0f603dfc24841eada6d284b60f0e#egg=gdata-origin_blogger_id_parsing
5a10
> html5lib==0.999999
7c12,14
< mf2py==0.2.6
---
> Jinja2==2.8
> MarkupSafe==0.23
> mf2py==0.2.7
9,13c16,20
< oauth2client==1.4.11
< oauthlib==1.0.1
< pyasn1==0.1.7
< pyasn1-modules==0.0.5
< python-tumblpy==1.0.4
---
> oauth2client==1.5.0
> oauthlib==1.0.3
> pyasn1==0.1.8
> pyasn1-modules==0.0.7
> python-tumblpy==1.0.5
16,17c23,24
< rsa==3.1.4
< simplejson==3.7.3
---
> rsa==3.2
> simplejson==3.8.0
19c26
< tweepy==3.3.0
---
> tweepy==3.4.0
21a29
> wheel==0.24.0
```

curent tentative proposal is to check in `pip freeze` output alongside the current `requirements.txt` files and have developers use that to create their virtualenvs.

btw @kylewm, i was wrong, `.lock` files aren't a thing after all. we just made up that suffix here at work, based on similar ruby/gem files. ¯\\\_(ツ)\_/¯

**Comment by kylewm** [comment]
I usually handle this by having requirements.txt literally just be the output of freeze. And then the high-level "direct" dependencies can live in setup.py

**Comment by snarfed** [comment]
sgtm! how do you install originally to generate the freeze then? `python setup.py install`?

**Comment by kylewm** [comment]
Hmm, I just `pip install` the dependencies as I need them. Usually at that point, I haven't created a setup.py yet (since I only tend to do that right before publishing to pypi)

**Comment by bear** [comment]
my preferred way of handling that is to have a Makefile with a couple different targets for the environment and dependencies - see https://github.com/bear/python-twitter/blob/master/Makefile for an example. The only tweak I would suggest is to not notice my using "sudo easy_install" to install pip ;)
