### ISSUE TITLE
404 from twitter /statuses/retweets API call

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#503]
currently hitting https://www.brid.gy/twitter/pierreozoux . looks like this happens [when the requested tweet is deleted](https://twitter.com/pierreozoux/status/651060335596670976). [`log`](https://www.brid.gy/log?start_time=1444166500&key=aglzfmJyaWQtZ3lyGAsSB1R3aXR0ZXIiC3BpZXJyZW96b3V4DA):

```
Fetching https://api.twitter.com/1.1/statuses/retweets.json?id=651060335596670976&since_id=651070539180720129
Error 404, response body: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}
Error 404, response body: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}
Error 404, response body: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}
HTTP Error 404: Not Found
Traceback (most recent call last):
File ".../tasks.py", line 81, in post
  source_updates.update(self.poll(source))
File ".../tasks.py", line 175, in poll
  response = source.get_activities_response(**kwargs)
File ".../models.py", line 229, in get_activities_response
  return self.gr_source.get_activities_response(**kwargs)
File ".../local/lib/python2.7/site-packages/granary/twitter.py", line 273, in get_activities_response
  tweet['retweets'] = self.urlopen(url)
File ".../local/lib/python2.7/site-packages/granary/twitter.py", line 722, in urlopen
  return request()
File ".../local/lib/python2.7/site-packages/granary/twitter.py", line 714, in request
  url, self.access_token_key, self.access_token_secret, **kwargs)
File ".../local/lib/python2.7/site-packages/oauth_dropins/twitter_auth.py", line 60, in signed_urlopen
  timeout=timeout)
...
HTTPError: HTTP Error 404: Not Found
```

**Comment by snarfed** [comment]
yeah, twitter docs seem to confirm this. https://dev.twitter.com/overview/api/response-codes
