### ISSUE TITLE
datastore transaction timeout in poll

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#514]
whenever a poll runs too long, the datastore transaction around updating the source (i think?) times out. this has been happening *forever*, just not often, so we haven't cared. [example log.](https://brid-gy.appspot.com/log?start_time=1445228936&key=aglzfmJyaWQtZ3lyGgsSDEZhY2Vib29rUGFnZSIIMzY4MDIyMzYM)

```
suspended generator run_to_queue(query.py:938) raised Timeout(The datastore operation timed out, or the data was temporarily unavailable.)
suspended generator helper(context.py:876) raised Timeout(The datastore operation timed out, or the data was temporarily unavailable.)
Traceback (most recent call last):
...
File "/base/data/home/apps/s~brid-gy/7.387946537313120088/tasks.py", line 83, in post
source_updates.update(self.poll(source))
File "/base/data/home/apps/s~brid-gy/7.387946537313120088/tasks.py", line 356, in poll
self.refetch_hfeed(source, source_updates)
File "/base/data/home/apps/s~brid-gy/7.387946537313120088/tasks.py", line 387, in refetch_hfeed
.order(-Response.created)):
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1774, in next
self._more_results) = self._fut.get_result()
...
File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1373, in check_rpc_success
raise _ToDatastoreError(err)
Timeout: The datastore operation timed out, or the data was temporarily unavailable.
```

**Comment by snarfed** [comment]
i diagnosed this wrong. it's a query timeout when repropagating old responses, almost the same thing as #515. we don't have a long-lived datastore transaction around poll after all. (glad i'm not that dumb. :P)
