### ISSUE TITLE
unit tests fail depending on order

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#546]
Fails:
```
$ python -m unittest test.test_tasks test.test_handlers
...
======================================================================
FAIL: test_author_uid_not_tag_uri (test.test_handlers.HandlersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kmahan/google_appengine/lib/mox/mox.py", line 1868, in new_method
    func(self, *args, **kwargs)
  File "test/test_handlers.py", line 127, in test_author_uid_not_tag_uri
    self.assertEqual(200, resp.status_int, resp.body)
AssertionError: HTTP Error 400: 400 Bad Request

The server could not comply with the request since it is either malformed or otherwise incorrect.

 fake 4 not found  
----------------------------------------------------------------------
Ran 107 tests in 9.292s

FAILED (failures=16)
```
But the reverse is fine:
```
$ python -m unittest test.test_handlers test.test_tasks
...
----------------------------------------------------------------------
Ran 107 tests in 9.479s

OK
```

**Comment by snarfed** [comment]
whee, nice catch! everything changes, everything breaks. :P

```
$ python -m unittest  -v test.test_tasks test.test_handlers.HandlersTest.test_author_uid_not_tag_uri
...
test_author_uid_not_tag_uri (test.test_handlers.HandlersTest) ... WARNING:root:Error 400, response body: 400 Bad Request

The server could not comply with the request since it is either malformed or otherwise incorrect.

 fake 4 not found  
ERROR:root:fake 4 not found
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "handlers.py", line 147, in get
    self.abort(400, '%s %s not found' % (source_short_name, string_id))
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 598, in abort
    abort(code, *args, **kwargs)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1830, in abort
    raise cls(*args, **kwargs)
HTTPClientError: fake 4 not found
FAIL

======================================================================
FAIL: test_author_uid_not_tag_uri (test.test_handlers.HandlersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/mox/mox.py", line 1868, in new_method
    func(self, *args, **kwargs)
  File "test/test_handlers.py", line 127, in test_author_uid_not_tag_uri
    self.assertEqual(200, resp.status_int, resp.body)
AssertionError: HTTP Error 400: 400 Bad Request

The server could not comply with the request since it is either malformed or otherwise incorrect.

 fake 4 not found  
```
