### ISSUE TITLE
FB RSVP with multi in-reply-to URLs throws an error

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#556]
@tantek was bitten by this. Sorry @tantek!

Here's his post as AS

```json
{
  "updated": "2015-11-20T11:41:00-0800", 
  "displayName": "going to Homebrew Website Club 17:30 @MozSF 2015-12-02!RSVP: kylewm.com/2015/12/sf-homebrew-website-clubFacebook fb.com/events/576323515852472", 
  "url": "http://tantek.com/2015/324/t2/homebrew-website-club-mozsf", 
  "object": [
    {
      "url": "https://kylewm.com/2015/12/sf-homebrew-website-club", 
      "displayName": "https://kylewm.com/2015/12/sf-homebrew-website-club", 
      "objectType": "note"
    }, 
    {
      "url": "https://www.facebook.com/events/576323515852472/", 
      "displayName": "https://www.facebook.com/events/576323515852472/", 
      "objectType": "note"
    }
  ], 
  "actor": {
    "url": "http://tantek.com/", 
    "image": {
      "url": "http://tantek.com/logo.jpg"
    }, 
    "displayName": "Tantek \u00c7elik", 
    "objectType": "person"
  }, 
  "content": "going to Homebrew Website Club 17:30 <a class=\"auto-link h-x-username\" href=\"https://twitter.com/MozSF\">@MozSF</a> 2015-12-02!<br class=\"auto-break\"/>RSVP: <a class=\"auto-link\" href=\"http://kylewm.com/2015/12/sf-homebrew-website-club\">kylewm.com/2015/12/sf-homebrew-website-club</a><br class=\"auto-break\"/>Facebook <a class=\"auto-link\" href=\"http://fb.com/events/576323515852472\">fb.com/events/576323515852472</a>", 
  "verb": "rsvp-yes", 
  "published": "2015-11-20T11:41:00-0800", 
  "id": "http://tantek.com/2015/324/t2/homebrew-website-club-mozsf", 
  "objectType": "activity"
}
```

Exception:
```
Error:  'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/7.388695683634510035/publish.py", line 206, in _run
    result = self.attempt_single_item(item)
  File "/base/data/home/apps/s~brid-gy/7.388695683634510035/publish.py", line 287, in attempt_single_item
    self.preprocess(obj, ignore_formatting=ignore_formatting)
  File "/base/data/home/apps/s~brid-gy/7.388695683634510035/publish.py", line 357, in preprocess
    self.source.preprocess_for_publish(activity)
  File "/base/data/home/apps/s~brid-gy/7.388695683634510035/models.py", line 537, in preprocess_for_publish
    for tag in obj.get('tags', []):
AttributeError: 'list' object has no attribute 'get'
```

We're assuming `object` is a singular value (when it can be either single or a list) in at least one place: https://github.com/snarfed/granary/blob/6eda9eeeb2da458af5c18355de47c0faac6deb06/granary/microformats2.py#L144

**Comment by snarfed** [comment]
thanks for triaging!

i expect there are hundreds of places, if not thousands, that assume `object` is singular. i think it's just likes and reposts where it can be a list? we should definitely handle all those, and comment them, but maybe just those.

**Comment by kylewm** [comment]
likes, reposts, and rsvps I guess.

**Comment by tantek** [comment]
I'm definitely confused. I've been doing multi-reply RSVPs for quite some time and using Bridgy Publish to FB no problem. I think this is a regression since 2015-11-04 (when I successfully Bridgy Publish RSVPd to FB from http://tantek.com/2015/308/t3/homebrew-website-club-mozsf

**Comment by snarfed** [comment]
thanks @kylewm!

any idea why this was working for tantek before?

**Comment by kylewm** [comment]
it was dying while processing person tags which was added in the last couple weeks. (i went back and checked granary from a couple of months ago to confirm that it also generated a list of objects for this post)

**Comment by snarfed** [comment]
aha, makes sense. thanks!
