### ISSUE TITLE
occasional propagate crash: assert self.entity.status == 'processing'

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#610]
happens maybe once or twice a week these days? not sure. either multiple propagate tasks are colliding, or one is dying early and not releasing its lease on the `Response` entity.

this one was [aglzfmJya...](https://console.developers.google.com/datastore/editentity?project=brid-gy&kind=Response&queryType=GQLQuery&queryText&key=0/|8/Response|44/name:tag:twitter.com,2013:690190681214685184) , for https://brid.gy/twitter/dominik. the webmention itself sent ok.

```
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/7.390126916268461327/tasks.py", line 676, in post
    self.send_webmentions()
  File "/base/data/home/apps/s~brid-gy/7.390126916268461327/tasks.py", line 462, in send_webmentions
    self.do_send_webmentions()
  File "/base/data/home/apps/s~brid-gy/7.390126916268461327/tasks.py", line 549, in do_send_webmentions
    self.complete()
...
  File "/base/data/home/apps/s~brid-gy/7.390126916268461327/tasks.py", line 596, in complete
    assert self.entity.status == 'processing'
AssertionError
```

**Comment by snarfed** [comment]
i started to think this was caused by #237, specifically ef748e7bda9a4d272f28d5f707efa9adfeb1d9c9, but that would have killed it well before it was able to send the webmention.

**Comment by snarfed** [comment]
i misdiagnosed this a bit. the `Response` entity in the datastore is `processing`, as expected. it's the entity *in memory* that's incorrectly `complete`. what the i don't even?! no clue what's going on.

**Comment by snarfed** [comment]
still happening as of 2017/03/15.

**Comment by snarfed** [comment]
still happening as of 2017/07/24. (search logs for `github.com/snarfed/bridgy/issues/610`.)

**Comment by snarfed** [comment]
not seeing it in the last 30d of logs. if it's still not happening next time i check, i may close this issue.

**Comment by snarfed** [comment]
still happening as of 2019/03/04.

**Comment by snarfed** [comment]
hasn't happened since at least the python 3 migration, mid december 2019. 🤞?

**Comment by snarfed** [comment]
still nothing since mid december 2019. somehow the python3 runtime fixed this?! ok then!
