### ISSUE TITLE
flaky test due to timestamp handling: test_social_user_page_mf2

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#630]
saw this fail for the first time locally just now. evidently our timestamp handling isn't entirely deterministic. this test renders a user page, mf2 parses it, and checks the resulting properties. it failed because a response's `dt-updated` was a second ahead.

that timestamp is rendered with this (old) django template snippet, `<time class="dt-updated" datetime="{{ response.updated|date:'c' }}" ...`, where `response.updated` is a `datetime` with ms accuracy. [in the test, we assert that it's](https://github.com/snarfed/bridgy/blob/f8a0202175ca8a69f923d441978482fad1436405/test/test_app.py#L282) `response.updated.replace(microsecond=0).isoformat()`.

my guess is that django's `date` filter might actually round up sometimes...? not sure.

```
FAIL: test_social_user_page_mf2 (test.test_app.AppTest)
Check the custom mf2 we render on social user pages.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/mox/mox.py", line 1868, in new_method
    func(self, *args, **kwargs)
  File "/Users/ryan/src/bridgy/test/test_app.py", line 283, in test_social_user_page_mf2
    props['updated'])
AssertionError: Lists differ: ['2016-03-02T14:40:14'] != [u'2016-03-02T14:40:15']

First differing element 0:
2016-03-02T14:40:14
2016-03-02T14:40:15

- ['2016-03-02T14:40:14']
?                     ^

+ [u'2016-03-02T14:40:15']
?  +                   ^
```

**Comment by snarfed** [comment]
still happening. :(
