### ISSUE TITLE
preview: UnboundLocalError: local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#684]
for https://brid.gy/twitter/PTALLC , on https://peachtreetranscription.com/healthcare-welcomes-bitcoin/

https://console.cloud.google.com/errors/9747061159911915517

[log](https://brid.gy/log?start_time=1468349275&key=aglzfmJyaWQtZ3lyZgsSDVB1Ymxpc2hlZFBhZ2UiP2h0dHBzOi8vcGVhY2h0cmVldHJhbnNjcmlwdGlvbi5jb20vaGVhbHRoY2FyZS13ZWxjb21lcy1iaXRjb2luLwwLEgdQdWJsaXNoGICAgIDA4YoKDA):

```
2016-07-12 18:47:46.535840 I Params: [(u'source', u'https://peachtreetranscription.com/healthcare-welcomes-bitcoin/'), (u'target', u'http://brid.gy/publish/twitter'), (u'bridgy_omit_link', u'false'), (u'source_key', u'aglzfmJy...')]
2016-07-12 18:47:46.724540 I Source: https://brid.gy/twitter/PTALLC , features [u'publish', u'listen'], status enabled, poll status ok
2016-07-12 18:47:47.330760 D Publish entity: aglzfmJyaWQtZ3lyZgsSDVB1Ymxpc2hlZFBhZ2UiP2h0dHBzOi8vcGVhY2h0cmVldHJhbnNjcmlwdGlvbi5jb20vaGVhbHRoY2FyZS13ZWxjb21lcy1iaXRjb2luLwwLEgdQdWJsaXNoGICAgIDA4YoKDA
2016-07-12 18:47:47.727310 I requests.get https://peachtreetranscription.com/healthcare-welcomes-bitcoin/ {'headers': {'User-Agent': '...'}}
2016-07-12 18:47:52.930230 D Parsed microformats2: {
...
"items": [
{
"type": [
"h-as-article"
],
"properties": {
"url": [
"https://checkmention.appspot.com/content/155dba0133d/68ad58a0c5213af24169a03eb644d998a9a54e6a/success",
"https://checkmention.appspot.com/content/155dba0133d/68ad58a0c5213af24169a03eb644d998a9a54e6a/hcardxss",
"https://checkmention.appspot.com/content/155dba0133d/68ad58a0c5213af24169a03eb644d998a9a54e6a/xss",
"https://www.apple.com/pr/bios/jonathan-ive.html",
"https://plus.google.com/https://plus.google.com/+Peachtreetranscription",
"https://twitter.com/Ptallc"
],
"photo": [
"https://checkmention.appspot.com/static/img/check.png",
"https://checkmention.appspot.com/static/img/q.jpg",
"https://checkmention.appspot.com/static/img/q.jpg",
"https://checkmention.appspot.com/static/img/ive.png"
],
"name": [
"Improving patient documentation for over 25 years!...(length 32644)
2016-07-12 18:47:55.814910 E local variable 'result' referenced before assignment
Traceback (most recent call last):
...
File "/base/data/home/apps/s~brid-gy/7.394062466126816950/publish.py", line 503, in post
  result = self._run()
File "/base/data/home/apps/s~brid-gy/7.394062466126816950/publish.py", line 296, in _run
  return result
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by snarfed** [comment]
looks like the fix is just `s/resp/result/` [here](https://github.com/snarfed/bridgy/blob/7ec508a9c35f2a6c3f06c009dc485ccbf254a734/publish.py#L248), but i haven't managed to repro the failure in a test yet. attempting to preview that page on prod does repro it though.
