### ISSUE TITLE
flickr publish: big files hit app engine's 10MB request limit

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#690]
app engine limits outgoing HTTP requests to 10MB.
* https://cloud.google.com/appengine/docs/python/outbound-requests#quotas_and_limits
* https://cloud.google.com/appengine/docs/python/refdocs/modules/google/appengine/api/urlfetch (search for _10 MiB_)

flickr's upload API expects us to send file contents in a single HTTP request - https://www.flickr.com/services/api/upload.api.html - which seems to mean that we can't upload photos or videos over 10MB.

flickr has an "async" upload API, https://www.flickr.com/services/api/upload.async.html , but it doesn't seem to help with this.

cc @kylewm in case he knows anything i don't! otherwise, i guess we just need to detect >10MB files and fail fast. :/

discovered by @tantek while trying to publish http://tantek.com/2016/205/t2/this-is-freedom-trails-clean-air-run . [log](https://brid.gy/log?start_time=1469343397&key=aglzfmJyaWQtZ3lyaQsSDVB1Ymxpc2hlZFBhZ2UiQmh0dHA6Ly90YW50ZWsuY29tLzIwMTYvMjA1L3QyL3RoaXMtaXMtZnJlZWRvbS10cmFpbHMtY2xlYW4tYWlyLXJ1bgwLEgdQdWJsaXNoGICAgICA8ogKDA):

```
urlopen GET https://instagram.fsjc1-3.fna.fbcdn.net/t50.2886-16/13836410_299979437016407_356815428_n.mp4 {}
requests.post https://up.flickr.com/services/upload {'files': {'photo': <addinfourl at 4215432696L whose fp = <socket._fileobject object at 0xfb43e1b0>>}, 'data': [('title', 'This is freedom. Open trails. Fresh clean air. Being able to run and breathe once again. #nofilter\n\n#freedom #trail #open #access #fresh #clean #air #breathe #breathing #run #running #hill #hills #fromwhereirun #view #fog #intofog #intoclouds'), ('description', '(Originally published at: http://tantek.com/2016/205/t2/this-is-freedom-trails-clean-air-run)'), ('tags', 'nofilter,freedom,trail,open,access,fresh,clean,air,breathe,breathing,run,running,hill,hills,fromwhereirun,view,fog,intofog,intoclouds'), ('oauth_nonce', '...'), ('oauth_timestamp', '1469343396'), ('oauth_version', '1.0'), ('oauth_signature_method', 'HMAC-SHA1'), ('oauth_consumer_key', '...'), ('oauth_token', '...'), ('oauth_signature', '...=')]}
2016-07-24 06:56:37.148839 W Error: Request exceeds 10 MiB limit for URL: https://up.flickr.com/services/upload
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/publish.py", line 261, in _run
result = self.attempt_single_item(item)
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/publish.py", line 381, in attempt_single_item
obj, include_link=include_link, ignore_formatting=ignore_formatting)
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/local/lib/python2.7/site-packages/granary/flickr.py", line 95, in create
ignore_formatting=ignore_formatting)
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/local/lib/python2.7/site-packages/granary/flickr.py", line 194, in _create
resp = self.upload(params, file)
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/local/lib/python2.7/site-packages/granary/flickr.py", line 77, in upload
params, file, self.access_token_key, self.access_token_secret)
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/local/lib/python2.7/site-packages/oauth_dropins/flickr_auth.py", line 128, in upload
resp = util.requests_post(upload_url, data=data, files={'photo': file})
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py", line 1023, in call
return getattr(requests, fn)(url, *args, **kwargs)
...
File "/base/data/home/apps/s~brid-gy/7.394388751838889354/local/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
raise ConnectionError(err, request=request)
ConnectionError: Request exceeds 10 MiB limit for URL: https://up.flickr.com/services/upload
```

**Comment by snarfed** [comment]
handled by snarfed/granary@826fbae9ff6c90f7a01d37a1eca131288151f4a2

**Comment by kylewm** [comment]
👍 I looked over the Flickr API and it didn't seem to have any kind of chunked uploading like the others do...so I think this is the best we can do. Maybe Verizon will fix this when they take over!
