### ISSUE TITLE
propagate blogpost crash on missing source

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#708]
```
Traceback (most recent call last):
...
File "webapp2-2.3/webapp2.py", line 545, in dispatch
  return method(*args, **kwargs)
File "tasks.py", line 744, in post
  source_domains = self.entity.source.get().domains
AttributeError: 'NoneType' object has no attribute 'domains'
```

datastore key:

```
aglzfmJyaWQtZ3ly2AILEghCbG9nUG9zdCLJAmh0dHBzOi8vbWVkaXVtLmNvbS9AaG9seXdhcnNydS8lRDAlQjElRDAlQjglRDElODIlRDAlQjIlRDElOEItJUQwJUI0JUQwJUJFLSVEMCVCRSVEMCVCRCVEMCVCQiVEMCVCMCVEMCVCOSVEMCVCRCVEMCVCRSVEMCVCMiVEMCVCRSVEMCVCOS0lRDAlQkElRDElODAlRDAlQkUlRDAlQjIlRDAlQjgtMy0lRDElODElRDAlQjUlRDElODAlRDAlQjIlRDAlQjglRDElODElRDAlQjAtJUQwJUI0JUQwJUJCJUQxJThGLSVEMSU4MSVEMCVCRiVEMCVCRSVEMSU4MCVEMSU4OSVEMCVCOCVEMCVCQSVEMCVCRSVEMCVCMi1lYWQyMzM5Y2M4ZmE_c291cmNlPXJzcy03YjBmZDQxZWQyOWMtLS0tLS0yDA
```

**Comment by snarfed** [comment]
haven't seen this again. closing.
