### ISSUE TITLE
bump up photo upload HTTP request timeouts

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#725]
right now at least the flickr one is just 15s, and we hit it earlier today while uploading a photo of @tantek's. [log](https://brid.gy/log?start_time=1486346702&key=aglzfmJyaWQtZ3lyYAsSDVB1Ymxpc2hlZFBhZ2UiOWh0dHA6Ly90YW50ZWsuY29tLzIwMTcvMDM2L3QxL2ZpbmlzaGVycy1waG90by1ydW5zdXJmY2l0eQwLEgdQdWJsaXNoGICAgICA8ogKDA):

```
Params: [('target', u'http://brid.gy/publish/flickr'), ('source', u'http://tantek.com/2017/036/t1/finishers-photo-runsurfcity')]
Source: https://www.brid.gy/flickr/39039882@N00 , features [u'publish', u'listen'], status enabled, poll status ok
...
publishing object type note to Flickr
urlopen GET https://scontent-lax3-2.cdninstagram.com/t51.2885-15/e35/16465047_195466020930658_3241869361157242880_n.jpg {}
requests.post https://up.flickr.com/services/upload {'files': {'photo': <addinfourl at 4241600600L whose fp = <socket._fileobject object at 0xfcae7e70>>}, 'data': [...
Flickr API error: (<requests.packages.urllib3.contrib.appengine.AppEngineManager object at 0xfcc02d50>, DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: https://up.flickr.com/services/upload',))
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/publish.py", line 265, in _run
    result = self.attempt_single_item(item)
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/publish.py", line 389, in attempt_single_item
    obj, include_link=include_link, ignore_formatting=ignore_formatting)
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/granary/flickr.py", line 95, in create
    ignore_formatting=ignore_formatting)
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/granary/flickr.py", line 196, in _create
    resp = self.upload(params, file)
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/granary/flickr.py", line 77, in upload
    params, file, self.access_token_key, self.access_token_secret)
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/oauth_dropins/flickr_auth.py", line 130, in upload
    resp = util.requests_post(upload_url, data=data, files={'photo': file})
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py", line 1078, in call
    return getattr(requests, fn)(url, *args, **kwargs)
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
...
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/requests_toolbelt/adapters/appengine.py", line 123, in urlopen
    **response_kw)
  File "/base/data/home/apps/s~brid-gy/7.398895598585198049/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/appengine.py", line 109, in urlopen
    raise TimeoutError(self, e)
TimeoutError: (<requests.packages.urllib3.contrib.appengine.AppEngineManager object at 0xfcc02d50>, DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: https://up.flickr.com/services/upload',))
```

**Comment by snarfed** [comment]
on second thought, not sure if we want to do this after all. [this photo is just 191KB](https://scontent-lax3-2.cdninstagram.com/t51.2885-15/e35/16465047_195466020930658_3241869361157242880_n.jpg), so we probably hit flickr's deadline due to their API flakiness, not slow upload with a big photo.

**Comment by snarfed** [comment]
we now return HTTP 504 Gateway Timeout on this kind of error, which is probably good enough. tentatively closing.
