### ISSUE TITLE
Bridgy Error: Could not fetch source URL

### ISSUE THREAD

**Issue by khurtwilliams** [snarfed/bridgy#827]
Getting the following error when I try to syndicate to Twitter or Facebook on first publishing.

E.g.

`Bridgy Error: Could not fetch source URL https://islandinthenet.com/juicy-hazy-india-pale-ale/Could not fetch source URL https://islandinthenet.com/juicy-hazy-india-pale-ale/`

The error does not occur if I "Update" the post.

**Comment by snarfed** [comment]
looking at the log is useful for these cases: click the "n hours ago" link next to the publish attempt in https://brid.gy/twitter/khurtwilliams#publishes .

in this case, [your site returned a 500 when bridgy tried to fetch that page](https://brid.gy/log?start_time=1527336877&key=aglzfmJyaWQtZ3lyXAsSDVB1Ymxpc2hlZFBhZ2UiNWh0dHBzOi8vaXNsYW5kaW50aGVuZXQuY29tL2p1aWN5LWhhenktaW5kaWEtcGFsZS1hbGUvDAsSB1B1Ymxpc2gYgICAgICAgAoM):

```
2018-05-26 12:14:32.009130 I requests.get https://islandinthenet.com/juicy-hazy-india-pale-ale/ {'headers': {'User-Agent': u'...'}}
2018-05-26 12:14:37.186910 W Error 500, response body: u'<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n\t<title>Database Error</title>\n\n</head>\n<body>\n\t<h1>Error establishing a database connection</h1>\n</body>\n</html>\n'
2018-05-26 12:14:37.187220 I Converting code ... to 502
2018-05-26 12:14:37.187340 I Could not fetch source URL https://islandinthenet.com/juicy-hazy-india-pale-ale/
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/8.409738577936094269/webmention.py", line 63, in fetch_mf2
fetched.raise_for_status()
File "/base/data/home/apps/s~brid-gy/8.409738577936094269/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: None for url: https://islandinthenet.com/juicy-hazy-india-pale-ale/
```

**Comment by snarfed** [comment]
notably, your site said _Error establishing a database connection_. maybe transient?

(also i much prefer old school new england style IPAs or west coast IBU bombs to the new juicy, haze styles. [had a similar conversation a bit ago.](https://twitter.com/search?f=tweets&q=%40dewitt ipa) vive la difference.)

**Comment by snarfed** [comment]
tentatively closing.
