### ISSUE TITLE
publish: some 401/403 errors from user's site incorrectly disable source

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#845]
in `publish.py`, we wrap the source's `create()` in a `try`/`except`. when it catches an HTTP 401 or 403 (for some silos), it disables the source.

however, some `create()`s make HTTP fetches elsewhere. e.g. for uploading photos or videos to twitter, we fetch them from the user's site first. if one of those fetches 401s or 403s, we incorrectly think that came from the silo API, and disable the account. we shouldn't.

code:
https://github.com/snarfed/bridgy/blob/e90724b4f654862315a790dd945b2a3c4a5aac4b/publish.py#L269-L271

[example log](https://brid.gy/log?start_time=1537879577&key=aglzfmJyaWQtZ3lySQsSDVB1Ymxpc2hlZFBhZ2UiImh0dHA6Ly9qZ3JlZ29yeW1jdmVycnkuY29tLzczNzctMi8MCxIHUHVibGlzaBiAgICAgICACgw) from yesterday when we did this to @jgmac1106 (sorry greg!):
```
I urlopen GET http://jgregorymcverry.com/wp-content/uploads/2018/09/IMG_20180924_130110-768x1024.jpg {}
W Error 403, response body: ...
W Disabling source due to: HTTP Error 403: Forbidden
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/8.412802474740472873/publish.py", line 252, in _run
  result = self.attempt_single_item(item)
File "/base/data/home/apps/s~brid-gy/8.412802474740472873/publish.py", line 433, in attempt_single_item
  obj, include_link=include_link, ignore_formatting=ignore_formatting)
File "/base/data/home/apps/s~brid-gy/8.412802474740472873/local/lib/python2.7/site-packages/granary/twitter.py", line 624, in create
  ignore_formatting=ignore_formatting)
File "/base/data/home/apps/s~brid-gy/8.412802474740472873/local/lib/python2.7/site-packages/granary/twitter.py", line 832, in _create
  ret = self.upload_images(images)
File "/base/data/home/apps/s~brid-gy/8.412802474740472873/local/lib/python2.7/site-packages/granary/twitter.py", line 924, in upload_images
  image_resp = util.urlopen(url)
File "/base/data/home/apps/s~brid-gy/8.412802474740472873/local/lib/python2.7/site-packages/oauth_dropins/webutil/util.py", line 1273, in urlopen
  return urllib_urlopen(url_or_req, *args, **kwargs)
...
HTTPError: HTTP Error 403: Forbidden
```

**Comment by jgmac1106** [comment]
Don’t apologize for fixing 5hings that make my website better. Happy to be the canary in the mine.

(Originally published at: http://jgregorymcverry.com/7454-2/)

**Comment by snarfed** [comment]
Obsolete, Bridgy Twitter is dead. https://github.com/snarfed/bridgy/issues/1410#issuecomment-1497763725
