### ISSUE TITLE
instagram scraping broken again

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#851]
...i think? not entirely sure yet. ugh. whee. i'm _this close_ to dropping instagram backfeed entirely.

[example circle build](https://circleci.com/gh/snarfed/granary/1288):

```
INFO:root:requests.get https://www.instagram.com/snarfed/ {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com:443
DEBUG:urllib3.connectionpool:https://www.instagram.com:443 "GET /snarfed/ HTTP/1.1" 200 17855
INFO:root:requests.get https://www.instagram.com/p/BqA1eVagN8b/ {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com:443
DEBUG:urllib3.connectionpool:https://www.instagram.com:443 "GET /p/BqA1eVagN8b/ HTTP/1.1" 200 9628
INFO:root:requests.get https://www.instagram.com/graphql/query/?query_hash=e0f59e4a1c8d78d0161873bc2ee7ec44&variables={"shortcode":"BqA1eVagN8b","include_reel":false,"first":24} {'headers': {u'Cookie': u'...'}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com:443
DEBUG:urllib3.connectionpool:https://www.instagram.com:443 "GET /graphql/query/?query_hash=e0f59e4a1c8d78d0161873bc2ee7ec44&variables=%7B%22shortcode%22:%22BqA1eVagN8b%22,%22include_reel%22:false,%22first%22:24%7D HTTP/1.1" 403 0
WARNING:root:Error 403, response body: u''
E
======================================================================
ERROR: test_live (__main__.InstagramTestLive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./instagram_live_test.py", line 26, in test_live
    fetch_replies=True, fetch_likes=True)
  File "/root/project/granary/instagram.py", line 220, in get_activities_response
    cookie=cookie, fetch_extras=fetch_replies or fetch_likes, cache=cache)
  File "/root/project/granary/instagram.py", line 359, in _scrape
    resp.text, cookie=cookie, count=count, fetch_extras=fetch_extras)
  File "/root/project/granary/instagram.py", line 873, in html_to_activities
    data = self._scrape_json(HTML_LIKES_URL % shortcode, cookie=cookie or self.cookie)
  File "/root/project/granary/instagram.py", line 895, in _scrape_json
    resp.raise_for_status()
  File "/root/project/local/local/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden for url: https://www.instagram.com/graphql/query/?query_hash=e0f59e4a1c8d78d0161873bc2ee7ec44&variables=%7B%22shortcode%22:%22BqA1eVagN8b%22,%22include_reel%22:false,%22first%22:24%7D
```

**Comment by snarfed** [comment]
[example poll log](https://brid.gy/log?start_time=1543245254&key=aglzfmJyaWQtZ3lyGgsSCUluc3RhZ3JhbSILdG9reW9ncmluZ28M):

```
D Params: NestedMultiDict([('last_polled', u'2018-11-18-19-54-27'), ('source_key', u'aglzfmJy...')])
I Source: tokyogringo (Instagram) tokyogringo, https://brid.gy/instagram/tokyogringo
I Last poll: https://brid.gy/log?start_time=1543244292&key=aglzfmJyaWQtZ3lyGgsSCUluc3RhZ3JhbSILdG9reW9ncmluZ28M
I Updating tokyogringo (Instagram) /instagram/tokyogringo : {u'poll_status': u'polling', u'rate_limited': False, u'last_poll_attempt': datetime.datetime(2018, 11, 26, 15, 14, 14, 615356)}
D Using ETag None, last activity id 1915121734592555858_4123449198
I requests.get https://www.instagram.com/tokyogringo/ {}
I requests.get https://www.instagram.com/p/BqgmWi9hl35/ {}
I requests.get https://www.instagram.com/graphql/query/?query_hash=e0f59e4a1c8d78d0161873bc2ee7ec44&variables={"shortcode":"...","include_reel":false,"first":24} {'headers': {u'Cookie': u'...'}}
W Error 403, response body: u''
W Error 403, response body: u''
I Updating tokyogringo (Instagram) /instagram/tokyogringo : {u'poll_status': u'error'}
E 403 Client Error: None for url: https://www.instagram.com/graphql/query/?query_hash=e0f59e4a1c8d78d0161873bc2ee7ec44&variables=%7B%22shortcode%22:%22BqgmWi9hl35%22,%22include_reel%22:false,%22first%22:24%7D
Traceback (most recent call last):
...
File "tasks.py", line 95, in post
self.poll(source)
File "tasks.py", line 161, in poll
min_id=source.last_activity_id, cache=cache)
File "instagram.py", line 106, in get_activities_response
return self.gr_source.get_activities_response(*args, **kwargs)
File "local/lib/python2.7/site-packages/granary/instagram.py", line 220, in get_activities_response
cookie=cookie, fetch_extras=fetch_replies or fetch_likes, cache=cache)
File "local/lib/python2.7/site-packages/granary/instagram.py", line 359, in _scrape
resp.text, cookie=cookie, count=count, fetch_extras=fetch_extras)
File "local/lib/python2.7/site-packages/granary/instagram.py", line 873, in html_to_activities
data = self._scrape_json(HTML_LIKES_URL % shortcode, ...=cookie or self.cookie)
File "local/lib/python2.7/site-packages/granary/instagram.py", line 895, in _scrape_json
resp.raise_for_status()
File "local/lib/python2.7/site-packages/requests/models.py", line 939, in raise_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: None for url: https://www.instagram.com/graphql/query/?query_hash=e0f59e4a1c8d78d0161873bc2ee7ec44&variables=%7B%22shortcode%22:%22BqgmWi9hl35%22,%22include_reel%22:false,%22first%22:24%7D
```

**Comment by snarfed** [comment]
ruh roh. seems like instagram may have dropped individual likes from the web entirely. if you're logged out and open a profile page, eg , and hover over photos, you can see a _count_ of likes...but if you actually open one, eg https://www.instagram.com/p/Bqn5TylAbgB/ , it doesn't show any info on likes at all.

when i log in and i open that individual photo URL above, i see an _11 likes_ link that i can click, which shows the individual likes. behind the scenes, it fetches the same URL that bridgy tries to fetch, `https://www.instagram.com/graphql/query/?query_hash=e0f59e4a1c8d78d0161873bc2ee7ec44&variables={"shortcode":"BmbU2qSFXrR","include_reel":true,"first":24}`, but it succeeds instead of 403ing, since it includes my session cookie.

bad, bad sign. backfeed for IG may be on the chopping block. 😢

**Comment by snarfed** [comment]
i ended up adding my test instagram account's `sessionid` cookie to all fetches of the likes JSON. shh don't tell. 😁 we're back in business.
