### ISSUE TITLE
publish crash due to ndb: NotImplementedError: Passed bad option: 'transaction'

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#945]
started seeing this crash in publish, both preview and real publish, after a deploy last night: `NotImplementedError: Passed bad option: 'transaction'`. deploy was on the same google-cloud-ndb version as before, 1.1.1, and the only change i deployed was de8f64ca8150b1f43234c14f38f08ac8d70bea94, which is pretty unrelated, so i don't know what happened. i tried rolling back to the pre-deploy version of the code, but that didn't fix it, which is odd.

https://console.cloud.google.com/errors/CIXnva_Rq-mTsQE , stack trace below. i temporarily fixed it by temporarily removing `@ndb.transactional()` here:

https://github.com/snarfed/bridgy/blob/de8f64ca8150b1f43234c14f38f08ac8d70bea94/publish.py#L561-L567

```
Traceback (most recent call last):
...
  File "/srv/publish.py", line 717, in post
    result = self._run()
  File "/srv/publish.py", line 191, in _run
    self.entity = self.get_or_add_publish_entity(resolved_url)
  File "/srv/publish.py", line 550, in get_or_add_publish_entity
    return self._get_or_add_publish_entity(source_url)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_transaction.py", line 194, in transactional_inner_wrapper
    propagation=propagation,
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_transaction.py", line 72, in transaction
    return future.result()
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 190, in result
    self.check_success()
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 137, in check_success
    raise self._exception
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 309, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_retry.py", line 78, in retry_wrapper
    raise error
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_retry.py", line 73, in retry_wrapper
    result = yield result
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    yielded = self.generator.send(send_value)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_transaction.py", line 149, in _transaction_async
    raise e
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_transaction.py", line 138, in _transaction_async
    result = callback()
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_transaction.py", line 186, in callback
    return wrapped(*args, **kwargs)
  File "/srv/publish.py", line 563, in _get_or_add_publish_entity
    page = PublishedPage.get_or_insert(source_url)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_options.py", line 89, in wrapper
    return wrapped(*pass_args, **kwargs)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/utils.py", line 110, in positional_wrapper
    return wrapped(*args, **kwds)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/model.py", line 5755, in _get_or_insert
    **kw_model_args
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 190, in result
    self.check_success()
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 137, in check_success
    raise self._exception
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 309, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/model.py", line 5884, in get_or_insert
    entity = yield insert()
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 309, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/model.py", line 5873, in insert
    yield entity.put_async(_options=_options)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 309, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/model.py", line 5234, in put
    ds_key = yield _datastore_api.put(ds_entity, kwargs["_options"])
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    yielded = self.generator.send(send_value)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_datastore_api.py", line 390, in put
    batch = _get_commit_batch(transaction, options)
  File "/env/lib/python3.7/site-packages/google/cloud/ndb/_datastore_api.py", line 559, in _get_commit_batch
    raise NotImplementedError("Passed bad option: {!r}".format(key))
NotImplementedError: Passed bad option: 'transaction'
```

**Comment by snarfed** [comment]
i couldn't reproduce this locally with ndb 1.1.1. i redeployed with ndb 1.2.1 and `@ndb.transactional` back in, worked ok locally, crashed the same way on prod.

i suspect there's bad checkpointed data in the prod datastore itself that's tripping up ndb somehow.

**Comment by snarfed** [comment]
actually, no, it's crashing the same way in circle: https://app.circleci.com/pipelines/github/snarfed/bridgy/41/workflows/4971bb0a-080f-4dd3-a026-32f0dcd7dc01/jobs/1133

**Comment by snarfed** [comment]
reported this to the ndb people: https://github.com/googleapis/python-ndb/issues/433
